using NUnit.Framework;
using ReMap.Standalone.Core;
using System.Linq;
using UnityEngine;

namespace ReMap.Standalone.Tests
{
    public sealed class GameExportTests
    {
        [Test]
        public void GeneratesApexPropAndScriptProperties()
        {
            var document = new MapDocument { name = "Test map", gameTarget = GameTargets.R5Flowstate, editingMap = "mp_rr_desertlands_hu" };
            var item = new MapObject
            {
                displayName = "Crate",
                assetId = "apex:crate",
                gameModelPath = "mdl/props/crate.rmdl",
                position = ApexCoordinates.ToUnity(new Float3(256, -128, 64)),
                rotation = WorldView.ToData(ApexDisplay.UnityAngles(new Vector3(10, 20, 30))),
                scale = new Float3(2, 2, 2)
            };
            item.scriptProperties.Add(new ScriptProperty { scope = "kv", name = "solid", value = "6" });
            item.scriptProperties.Add(new ScriptProperty { scope = "s", name = "remapTag", value = "\"cover\"" });
            item.scriptProperties.Add(new ScriptProperty { scope = "", name = "customField", value = "42" });
            document.objects.Add(item);

            string code = ReMapGameScript.Generate(document, new[] { item });

            StringAssert.StartsWith("// Generated by ReMap for R5Flowstate.\n// Map source: ReMap project \"Test map\".", code.Replace("\r\n", "\n"));
            StringAssert.Contains("PrecacheModel( $\"mdl/props/crate.rmdl\" )", code);
            StringAssert.Contains("if ( GetMapName() != \"mp_rr_desertlands_hu\" )", code);
            StringAssert.Contains("entity ent", code);
            StringAssert.Contains("entity ent\n\tent = ReMap_CreateProp", code.Replace("\r\n", "\n"));
            StringAssert.Contains("ent = ReMap_CreateProp( $\"mdl/props/crate.rmdl\", <256, -128, 64>, <10, 20, 30>, true, 50000, -1, 2 )", code);
            StringAssert.Contains("ent.kv.solid = 6", code);
            StringAssert.Contains("ent.s.remapTag <- \"cover\"", code);
            StringAssert.Contains("ent.customField = 42", code);
            StringAssert.DoesNotContain("ent..customField", code);
            StringAssert.DoesNotContain("originOffset", code);
            string normalizedCode = code.Replace("\r\n", "\n");
            StringAssert.Contains("void function Sh_ReMap_PrecacheMap()\n{\n", normalizedCode);
            StringAssert.Contains("void function Sv_ReMap_LoadMap()\n{\n", normalizedCode);
            StringAssert.Contains("void function Cl_ReMap_LoadMap()\n{\n", normalizedCode);

            string live = ReMapGameScript.GenerateLiveCommands(document, new[] { item });
            StringAssert.StartsWith("script Sh_ReMap_Clear()", live);
            StringAssert.DoesNotContain("script ReMap_ClearZiplines()", live);
            StringAssert.Contains("script ReMap_CreateProp( $\"mdl/props/crate.rmdl\", <256, -128, 64>, <10, 20, 30>, true, 50000, -1, 2 )", live);
            StringAssert.DoesNotContain("entity remapLive", live);
            StringAssert.DoesNotContain("remapLive", live);
            StringAssert.DoesNotContain("script_server", live);
            StringAssert.DoesNotContain("originOffset", live);
        }

        [Test]
        public void NonZeroSceneOriginOffsetsPropsAndZiplinesOnlyInGame()
        {
            var document = new MapDocument
            {
                gameTarget = GameTargets.R5Flowstate,
                editingMap = "mp_rr_desertlands_hu",
                originOffset = ApexCoordinates.ToUnity(new Float3(100, 200, 300))
            };
            var prop = new MapObject
            {
                displayName = "Offset crate", assetId = "apex:crate", gameModelPath = "mdl/props/crate.rmdl",
                position = ApexCoordinates.ToUnity(new Float3(1, 2, 3))
            };
            var zipline = new MapObject { displayName = "Offset zipline", isGroup = true, customType = "zipline" };
            var start = new MapObject
            {
                parentId = zipline.id, customType = "zipline-endpoint", customRole = "start",
                position = ApexCoordinates.ToUnity(new Float3(10, 20, 30))
            };
            var end = new MapObject
            {
                parentId = zipline.id, customType = "zipline-endpoint", customRole = "end",
                position = ApexCoordinates.ToUnity(new Float3(40, 50, 60))
            };
            zipline.ziplineStartId = start.id; zipline.ziplineEndId = end.id;
            var world = new[] { prop, zipline, start, end };

            string code = ReMapGameScript.Generate(document, world);
            StringAssert.Contains("vector originOffset = <100, 200, 300>", code);
            StringAssert.Contains("<1, 2, 3> + originOffset", code);
            StringAssert.Contains("ReMap_CreateZipline( <10, 20, 30> + originOffset", code);
            StringAssert.Contains(", <40, 50, 60> + originOffset", code);

            string live = ReMapGameScript.GenerateLiveCommands(document, world);
            StringAssert.Contains("<101, 202, 303>", live);
            StringAssert.Contains("ReMap_CreateZipline( <110, 220, 330>", live);
            StringAssert.Contains(", <140, 250, 360>", live);
            StringAssert.DoesNotContain("originOffset", live);
        }

        [Test]
        public void RejectsMissingModelAndNonUniformScale()
        {
            var document = new MapDocument { editingMap = "mp_rr_desertlands_hu" };
            var missing = new MapObject { displayName = "No model" };
            Assert.Throws<System.ArgumentException>(() => ReMapGameScript.Generate(document, new[] { missing }));
            var stretched = new MapObject { displayName = "Stretched", gameModelPath = "mdl/x.rmdl", scale = new Float3(1, 2, 1) };
            Assert.Throws<System.ArgumentException>(() => ReMapGameScript.Generate(document, new[] { stretched }));
        }

        [Test]
        public void RequiresEditedApexMap()
        {
            var item = new MapObject { gameModelPath = "mdl/x.rmdl" };
            Assert.Throws<System.ArgumentException>(() => ReMapGameScript.Generate(new MapDocument(), new[] { item }));
        }

        [Test]
        public void ResetScriptRestoresTheThreeEmptyGeneratedFunctions()
        {
            string code = ReMapGameScript.GenerateReset(GameTargets.R5Flowstate);

            StringAssert.StartsWith("// Generated by ReMap for R5Flowstate", code);
            StringAssert.Contains("// Map source: reset script generated by the ReMap app.", code);
            StringAssert.Contains("Original ReMap by Zee", code);
            StringAssert.Contains("Made with love", code);
            StringAssert.Contains("Mauler125/r5sdk", code);
            StringAssert.Contains("void function Sh_ReMap_PrecacheMap()\n{\n\tPrecacheModel( $\"mdl/dev/empty.rmdl\" )\n}", code.Replace("\r\n", "\n"));
            StringAssert.Contains("void function Sv_ReMap_LoadMap() {}", code);
            StringAssert.Contains("void function Cl_ReMap_LoadMap() {}", code);
            StringAssert.DoesNotContain("ReMap_CreateProp", code);
            Assert.That(code.Split(new[] { "PrecacheModel" }, System.StringSplitOptions.None).Length - 1, Is.EqualTo(1));
        }

        [Test]
        public void GeneratedMapUsesSharedServerAndClientNutFiles()
        {
            Assert.That(ReMapGameScript.GeneratedFileNames, Is.EqualTo(new[] { "sh_remap.nut", "sv_remap_map.nut", "cl_remap_map.nut" }));
        }

        [Test]
        public void ScriptPropertiesAreDeepCopiedAndValidated()
        {
            var document = new MapDocument();
            var item = new MapObject { gameModelPath = "mdl/x.rmdl" };
            item.scriptProperties.Add(new ScriptProperty { scope = "e", name = "preventStickyEnts", value = "true" });
            document.objects.Add(item);
            var copy = document.Copy();
            copy.objects[0].scriptProperties[0].value = "false";
            Assert.That(document.objects[0].scriptProperties[0].value, Is.EqualTo("true"));
            document.Validate();
            item.scriptProperties[0].name = "bad.name";
            Assert.Throws<System.ArgumentException>(document.Validate);
            item.scriptProperties[0] = new ScriptProperty { scope = "e", name = "solid", value = "6" };
            Assert.Throws<System.ArgumentException>(document.Validate);
        }

        [Test]
        public void ClassicPropSettingsUseLegacyDefaultsAndSurviveSaveMigration()
        {
            var item = new MapObject();
            Assert.That(item.allowMantle, Is.True);
            Assert.That(item.fadeDistance, Is.EqualTo(50000f));
            Assert.That(item.realmId, Is.EqualTo(-1));
            Assert.That(item.clientSide, Is.False);

            string legacy = "{\"schemaVersion\":1,\"coordinateSystem\":\"unity-y-up-meters\",\"objects\":[{" +
                "\"id\":\"" + item.id + "\",\"assetId\":\"apex:crate\",\"displayName\":\"Crate\"}]}";
            var migrated = new UnityMapCodec().Decode(legacy);
            Assert.That(migrated.objects[0].allowMantle, Is.True);
            Assert.That(migrated.objects[0].fadeDistance, Is.EqualTo(50000f));
            Assert.That(migrated.objects[0].realmId, Is.EqualTo(-1));

            item.allowMantle = false; item.fadeDistance = 12345f; item.realmId = 7; item.clientSide = true;
            var document = new MapDocument(); document.objects.Add(item);
            var roundTrip = new UnityMapCodec().Decode(new UnityMapCodec().Encode(document));
            Assert.That(roundTrip.objects[0].allowMantle, Is.False);
            Assert.That(roundTrip.objects[0].fadeDistance, Is.EqualTo(12345f));
            Assert.That(roundTrip.objects[0].realmId, Is.EqualTo(7));
            Assert.That(roundTrip.objects[0].clientSide, Is.True);
        }

        [Test]
        public void ExportsClassicServerAndClientPropSettingsForBothGames()
        {
            foreach (string target in new[] { GameTargets.R5Reloaded, GameTargets.R5Flowstate })
            {
                var document = new MapDocument { name = "Classic props", gameTarget = target, editingMap = "mp_rr_desertlands_64k_x_64k" };
                var server = new MapObject
                {
                    displayName = "Server crate", assetId = "apex:server", gameModelPath = "mdl/props/server.rmdl",
                    allowMantle = false, fadeDistance = 1200f, realmId = 4, scale = new Float3(1.5f, 1.5f, 1.5f)
                };
                var client = new MapObject
                {
                    displayName = "Client crate", assetId = "apex:client", gameModelPath = "mdl/props/client.rmdl",
                    clientSide = true, scale = new Float3(2f, 2f, 2f)
                };
                client.scriptProperties.Add(new ScriptProperty { scope = "kv", name = "renderamt", value = "255" });
                client.scriptProperties.Add(new ScriptProperty { scope = "e", name = "overheadRui", value = "null" });
                client.scriptProperties.Add(new ScriptProperty { scope = "s", name = "remapTag", value = "\"client\"" });
                document.objects.Add(server); document.objects.Add(client);

                string code = ReMapGameScript.Generate(document, document.objects);

                StringAssert.Contains("// File: remap/sv_remap_map.nut", code);
                StringAssert.Contains("void function Sv_ReMap_LoadMap()", code);
                StringAssert.Contains("ReMap_CreateProp( $\"mdl/props/server.rmdl\", <0, 0, 0>, <0, 0, 0>, false, 1200, 4, 1.5 )", code);
                StringAssert.Contains("// File: remap/cl_remap_map.nut", code);
                StringAssert.Contains("void function Cl_ReMap_LoadMap()", code);
                Assert.That(code.Split(new[] { "\tSh_ReMap_Clear()" }, System.StringSplitOptions.None).Length - 1, Is.EqualTo(2));
                StringAssert.Contains("ent = ReMap_CreateClientProp( $\"mdl/props/client.rmdl\", <0, 0, 0>, <0, 0, 0>, 2 )", code);
                StringAssert.Contains("ent.kv.renderamt = 255", code);
                StringAssert.Contains("ent.e.overheadRui = null", code);
                StringAssert.Contains("ent.s.remapTag <- \"client\"", code);
                StringAssert.Contains("PrecacheModel( $\"mdl/props/server.rmdl\" )", code);
                StringAssert.Contains("PrecacheModel( $\"mdl/props/client.rmdl\" )", code);
            }
        }

        [Test]
        public void ClientSideEntityFieldsOnlyOfferManualEntry()
        {
            var method = typeof(ReMapApp).GetMethod("PropertyChoices",
                System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static);
            Assert.That(method, Is.Not.Null);
            var serverChoices = (System.Collections.Generic.List<string>)method.Invoke(null, new object[] { "e", false });
            var clientChoices = (System.Collections.Generic.List<string>)method.Invoke(null, new object[] { "e", true });

            Assert.That(serverChoices.Count, Is.GreaterThan(1));
            Assert.That(clientChoices, Is.EqualTo(new[] { L.T("#MANUAL_FIELD") }));
        }

        [Test]
        public void ReusesOneEntityLocalBeyondTheSquirrelDeclarationLimit()
        {
            var document = new MapDocument { gameTarget = GameTargets.R5Flowstate, editingMap = "mp_rr_desertlands_hu" };
            var objects = Enumerable.Range(0, 300).Select(index => new MapObject
            {
                displayName = "Prop " + index,
                assetId = "apex:crate",
                gameModelPath = "mdl/props/crate.rmdl"
            }).ToArray();

            string code = ReMapGameScript.Generate(document, objects);

            Assert.That(code.Split(new[] { "entity ent" }, System.StringSplitOptions.None).Length - 1, Is.EqualTo(1));
            Assert.That(code.Split(new[] { "\tent = ReMap_CreateProp" }, System.StringSplitOptions.None).Length - 1, Is.EqualTo(300));
            StringAssert.DoesNotContain(" )\n\n\tent = ReMap_CreateProp", code.Replace("\r\n", "\n"));

        }

        [Test]
        public void R5ReloadedMapUsesTheUnifiedReMapApi()
        {
            var document = new MapDocument { gameTarget = GameTargets.R5Reloaded, editingMap = "mp_rr_desertlands_64k_x_64k" };
            var item = new MapObject { displayName = "Crate", assetId = "apex:crate", gameModelPath = "mdl/props/crate.rmdl" };
            string code = ReMapGameScript.Generate(document, new[] { item });
            string live = ReMapGameScript.GenerateLiveCommands(document, new[] { item });

            StringAssert.Contains("Sh_ReMap_Clear()", code);
            StringAssert.Contains("global function Sh_ReMap_PrecacheMap", code);
            StringAssert.Contains("void function Sh_ReMap_PrecacheMap()", code);
            StringAssert.Contains("global function Sv_ReMap_LoadMap", code);
            StringAssert.Contains("void function Sv_ReMap_LoadMap()", code);
            StringAssert.DoesNotContain("ReMapLive", code);
            StringAssert.Contains("ReMap_CreateProp( $\"mdl/props/crate.rmdl\", <0, 0, 0>, <0, 0, 0>, true, 50000, -1, 1 )", code);
            StringAssert.StartsWith("script Sh_ReMap_Clear()", live.Replace("\r\n", "\n"));
            StringAssert.DoesNotContain("MapEditor_", code);
            StringAssert.DoesNotContain("External_ReMapRemoveAllEnts", code);
        }

        [Test]
        public void InstallerUpdatesOnlyGeneratedFunctionsLeavesManifestUntouchedAndResetRestoresTemplates()
        {
            string platform = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "ReMapR5R-" + System.Guid.NewGuid().ToString("N"));
            string scripts = System.IO.Path.Combine(platform, "scripts", "vscripts");
            string remap = System.IO.Path.Combine(scripts, "remap");
            System.IO.Directory.CreateDirectory(remap);
            string shared = System.IO.Path.Combine(remap, "sh_remap.nut");
            string serverMap = System.IO.Path.Combine(remap, "sv_remap_map.nut");
            string clientMap = System.IO.Path.Combine(remap, "cl_remap_map.nut");
            try
            {
                string manifestPath = System.IO.Path.Combine(scripts, "scripts.rson");
                string originalManifest = "// managed manually\nWhen: \"SERVER\"\nScripts:\n[\n]\nWhen: \"CLIENT\"\nScripts:\n[\n]\n";
                System.IO.File.WriteAllText(manifestPath, originalManifest);
                System.IO.File.WriteAllText(System.IO.Path.Combine(scripts, "sh_init.gnut"), "void function Shared_Init()\n{\n  Sh_ReMap_Init()\n}\n");
                System.IO.File.WriteAllText(System.IO.Path.Combine(remap, "sv_remap_objects.nut"), "global function ReMap_CreateProp\n");
                System.IO.File.WriteAllText(System.IO.Path.Combine(remap, "sv_remap_ziplines.nut"), "global function ReMap_CreateZipline\n");
                System.IO.File.WriteAllText(System.IO.Path.Combine(remap, "cl_remap_objects.nut"), "global function ReMap_CreateClientProp\n");
                System.IO.File.WriteAllText(shared, "global const bool REMAP_LOAD_MAP = false\n// shared customization\nvoid function Sh_ReMap_PrecacheMap() {\n\tPrecacheModel( $\"mdl/dev/empty.rmdl\" )\n}\n");
                System.IO.File.WriteAllText(serverMap, "// server customization\nvoid function Sv_ReMap_LoadMap() {}\n");
                System.IO.File.WriteAllText(clientMap, "// client customization\nvoid function Cl_ReMap_LoadMap() {}\n");
                var document = new MapDocument { gameTarget = GameTargets.R5Reloaded, editingMap = "mp_rr_desertlands_64k_x_64k" };
                var server = new MapObject { displayName = "Server", gameModelPath = "mdl/props/server.rmdl" };
                var client = new MapObject { displayName = "Client", gameModelPath = "mdl/props/client.rmdl", clientSide = true };
                document.objects.Add(server); document.objects.Add(client);

                string path = ReMapGameScriptInstaller.Write(platform, document, document.objects);
                ReMapGameScriptInstaller.Write(platform, document, document.objects);

                Assert.That(path, Is.EqualTo(remap));
                StringAssert.Contains("global const bool REMAP_LOAD_MAP = true", System.IO.File.ReadAllText(shared));
                StringAssert.Contains("PrecacheModel( $\"mdl/props/server.rmdl\" )", System.IO.File.ReadAllText(shared));
                StringAssert.Contains("PrecacheModel( $\"mdl/props/client.rmdl\" )", System.IO.File.ReadAllText(shared));
                StringAssert.Contains("ReMap_CreateProp( $\"mdl/props/server.rmdl\"", System.IO.File.ReadAllText(serverMap));
                StringAssert.DoesNotContain("mdl/props/client.rmdl", System.IO.File.ReadAllText(serverMap));
                StringAssert.Contains("ReMap_CreateClientProp( $\"mdl/props/client.rmdl\"", System.IO.File.ReadAllText(clientMap));
                StringAssert.Contains("void function Sv_ReMap_LoadMap()\n{\n",
                    System.IO.File.ReadAllText(serverMap).Replace("\r\n", "\n"));
                StringAssert.Contains("void function Cl_ReMap_LoadMap()\n{\n",
                    System.IO.File.ReadAllText(clientMap).Replace("\r\n", "\n"));
                StringAssert.Contains("// shared customization", System.IO.File.ReadAllText(shared));
                StringAssert.Contains("// server customization", System.IO.File.ReadAllText(serverMap));
                StringAssert.Contains("// client customization", System.IO.File.ReadAllText(clientMap));
                foreach (string file in new[] { shared, serverMap, clientMap })
                    Assert.That(System.IO.File.Exists(file + ".remap.bak"), Is.True, file);

                ReMapGameScriptInstaller.Reset(platform, GameTargets.R5Reloaded);
                string resetShared = System.IO.File.ReadAllText(shared);
                string resetServer = System.IO.File.ReadAllText(serverMap);
                string resetClient = System.IO.File.ReadAllText(clientMap);
                StringAssert.Contains("global const bool REMAP_LOAD_MAP = false", resetShared);
                StringAssert.Contains("PrecacheModel( $\"mdl/dev/empty.rmdl\" )", resetShared);
                StringAssert.DoesNotContain("mdl/props/server.rmdl", resetShared);
                StringAssert.DoesNotContain("ReMap_CreateProp", resetServer);
                StringAssert.DoesNotContain("ReMap_CreateClientProp", resetClient);
                StringAssert.Contains("void function Sv_ReMap_LoadMap() {}", resetServer);
                StringAssert.Contains("void function Cl_ReMap_LoadMap() {}", resetClient);
                StringAssert.Contains("// shared customization", resetShared);
                StringAssert.Contains("// server customization", resetServer);
                StringAssert.Contains("// client customization", resetClient);
                Assert.That(System.IO.File.ReadAllText(manifestPath), Is.EqualTo(originalManifest));
                Assert.That(System.IO.File.Exists(manifestPath + ".remap.bak"), Is.False);
            }
            finally { if (System.IO.Directory.Exists(platform)) System.IO.Directory.Delete(platform, true); }
        }

        [TestCase(GameTargets.R5Reloaded, "sh_init.gnut", "_sh_init.gnut")]
        [TestCase(GameTargets.R5Flowstate, "_sh_init.gnut", "sh_init.gnut")]
        public void InstallerRequiresTheTargetSpecificSharedInit(
            string gameTarget, string expectedInit, string otherInit)
        {
            string platform = System.IO.Path.Combine(System.IO.Path.GetTempPath(),
                "ReMapInit-" + System.Guid.NewGuid().ToString("N"));
            string scripts = System.IO.Path.Combine(platform, "scripts", "vscripts");
            string remap = System.IO.Path.Combine(scripts, "remap");
            System.IO.Directory.CreateDirectory(remap);
            try
            {
                foreach (string file in new[] {
                    "sv_remap_objects.nut", "sv_remap_ziplines.nut", "sv_remap_map.nut",
                    "cl_remap_objects.nut", "cl_remap_map.nut", "sh_remap.nut"
                }) System.IO.File.WriteAllText(System.IO.Path.Combine(remap, file), "");
                const string init = "void function Shared_Init()\n{\n  Sh_ReMap_Init()\n}\n";
                System.IO.File.WriteAllText(System.IO.Path.Combine(scripts, otherInit), init);

                Assert.Throws<System.IO.InvalidDataException>(() =>
                    ReMapGameScriptInstaller.EnsureInstalled(platform, gameTarget));

                System.IO.File.WriteAllText(System.IO.Path.Combine(scripts, expectedInit), init);
                Assert.That(ReMapGameScriptInstaller.EnsureInstalled(platform, gameTarget),
                    Is.EqualTo(remap));
            }
            finally
            {
                if (System.IO.Directory.Exists(platform))
                    System.IO.Directory.Delete(platform, true);
            }
        }

        [Test]
        public void GeneratedModulesShareTheZiplineImplementation()
        {
            string root = System.IO.Path.GetFullPath(System.IO.Path.Combine(Application.dataPath, "..", "scripts", "vscripts"));
            string flowstate = System.IO.File.ReadAllText(System.IO.Path.Combine(root, "remap_r5f", "sv_remap_ziplines.nut"));
            string r5reloaded = System.IO.File.ReadAllText(System.IO.Path.Combine(root, "remap_r5r", "sv_remap_ziplines.nut"));

            StringAssert.Contains("REMAP_ZIPLINE_MODEL_ARM", flowstate);
            StringAssert.Contains("CreateEntity( \"zipline\" )", flowstate);
            StringAssert.DoesNotContain("MapEditor_", flowstate);
            StringAssert.Contains("endCableOrigin = <startCableOrigin.x, startCableOrigin.y, endCableOrigin.z>", flowstate);
            StringAssert.Contains("startCableAngles = <0.0, pushOffAngle, 0.0>", flowstate);
            StringAssert.DoesNotContain("startAngles.y + armYaw + pushOffAngle", flowstate);
            StringAssert.Contains("vector armAngles = <angles.x, angles.y + 90.0, angles.z>", flowstate);
            StringAssert.Contains("RotateVector( <4, -2.5, armHeight>, angles )", flowstate);
            StringAssert.Contains("return origin + RotateVector( <-58, -2, -14>, angles )", flowstate);
            StringAssert.Contains("return armOrigin + RotateVector( <-58, -2, -14>, angles )", flowstate);
            StringAssert.Contains("ReMap_CreateZipline", r5reloaded);
            StringAssert.Contains("CreateEntity( \"zipline\" )", r5reloaded);
            StringAssert.DoesNotContain("MapEditor_", r5reloaded);
            StringAssert.Contains("REMAP_ZIPLINE_MODEL_ARM", r5reloaded);
            StringAssert.Contains("endCableOrigin = <startCableOrigin.x, startCableOrigin.y, endCableOrigin.z>", r5reloaded);
            StringAssert.Contains("startCableAngles = <0.0, pushOffAngle, 0.0>", r5reloaded);
            StringAssert.DoesNotContain("startAngles.y + armYaw + pushOffAngle", r5reloaded);
            StringAssert.Contains("vector armAngles = <angles.x, angles.y + 90.0, angles.z>", r5reloaded);
            StringAssert.Contains("RotateVector( <4, -2.5, armHeight>, angles )", r5reloaded);
            StringAssert.Contains("security_fence_post", r5reloaded);
            StringAssert.Contains("return origin + RotateVector( <-58, -2, -14>, angles )", r5reloaded);
            StringAssert.Contains("return armOrigin + RotateVector( <-58, -2, -14>, angles )", r5reloaded);

            string flowstateProps = System.IO.File.ReadAllText(System.IO.Path.Combine(root, "remap_r5f", "sv_remap_objects.nut"));
            string reloadedProps = System.IO.File.ReadAllText(System.IO.Path.Combine(root, "remap_r5r", "sv_remap_objects.nut"));
            foreach (string props in new[] { flowstateProps, reloadedProps })
            {
                StringAssert.Contains("bool allowMantle = true", props);
                StringAssert.Contains("float fadeDistance = 50000.0", props);
                StringAssert.Contains("prop.RemoveFromAllRealms()", props);
                StringAssert.Contains("prop.AddToRealm( realmId )", props);
            }
            foreach (string variant in new[] { "remap_r5f", "remap_r5r" })
            {
                string clientProps = System.IO.File.ReadAllText(System.IO.Path.Combine(root, variant, "cl_remap_objects.nut"));
                StringAssert.Contains("CreateClientSidePropDynamic( origin, angles, model )", clientProps);
                StringAssert.Contains("prop.SetModelScale( scale )", clientProps);
            }
        }

        [Test]
        public void GeneratedPublicFunctionsUseTheReMapPrefix()
        {
            string root = System.IO.Path.GetFullPath(System.IO.Path.Combine(Application.dataPath, "..", "scripts", "vscripts"));
            string[] variants = { "remap_r5r", "remap_r5f" };
            foreach (string variant in variants)
            {
                string variantRoot = System.IO.Path.Combine(root, variant);
                Assert.That(System.IO.Directory.GetFiles(variantRoot, "*.gnut"), Is.Empty, variant + " contains an unexpected global script.");
                foreach (string path in System.IO.Directory.GetFiles(variantRoot, "*.nut"))
                {
                    string code = System.IO.File.ReadAllText(path);
                    StringAssert.StartsWith("// Generated by ReMap for ", code, path);
                    StringAssert.Contains("// Source code: https://github.com/ReMap", code, path);
                    StringAssert.DoesNotContain("preserved from the source", code, path);
                    StringAssert.DoesNotContain("scripts/vscripts/source", code, path);
                    foreach (System.Text.RegularExpressions.Match match in System.Text.RegularExpressions.Regex.Matches(code, @"(?m)^global function\s+(\w+)"))
                        StringAssert.IsMatch(@"^(?:ReMap_|Sh_ReMap_|Sv_ReMap_|Cl_ReMap_)", match.Groups[1].Value, path);
                }
            }
        }
    }
}
