using ReMap.Standalone.Core;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEngine;
using UnityEngine.UIElements;

namespace ReMap.Standalone
{
    public static class ReMapGameScript
    {
        public const string DirectoryName = "remap";
        public const string SharedFileName = "sh_remap.nut";
        public const string ServerMapFileName = "sv_remap_map.nut";
        public const string ClientMapFileName = "cl_remap_map.nut";
        public static readonly string[] GeneratedFileNames = { SharedFileName, ServerMapFileName, ClientMapFileName };

        public static string GenerateReset(string gameTarget = GameTargets.R5Reloaded)
        {
            gameTarget = GameTargets.Normalize(gameTarget);
            return RenderEdits(gameTarget, "Map source: reset script generated by the ReMap app.", ResetEdits(gameTarget));
        }

        public static string Generate(MapDocument document, IEnumerable<MapObject> worldObjects,
            IEnumerable<string> selectedRpaks = null)
        {
            if (document == null) throw new ArgumentNullException(nameof(document));
            return RenderEdits(GameTargets.Normalize(document.gameTarget), MapSourceDescription(document),
                BuildEdits(document, worldObjects, selectedRpaks));
        }

        internal static IReadOnlyList<ReMapGameScriptEdit> BuildEdits(MapDocument document,
            IEnumerable<MapObject> worldObjects, IEnumerable<string> selectedRpaks = null)
        {
            if (document == null) throw new ArgumentNullException(nameof(document));
            GameTargets.Normalize(document.gameTarget);
            string map = EditingMap(document);
            var world = (worldObjects ?? throw new ArgumentNullException(nameof(worldObjects))).Where(o => o != null).ToList();
            var objects = Prepare(world);
            var serverObjects = objects.Where(o => !o.clientSide).ToList();
            var clientObjects = objects.Where(o => o.clientSide).ToList();
            var models = objects.Select(Model).Distinct(StringComparer.OrdinalIgnoreCase).ToList();
            models.AddRange(world.Where(o => o.customType == "door")
                .Select(o => ReMapDoorProfiles.Find(o.doorType).ModelPath)
                .Where(model => !models.Contains(model, StringComparer.OrdinalIgnoreCase)));
            if (world.Any(o => o.customType == "loot-bin") &&
                !models.Contains(ReMapApp.LootBinModelPath, StringComparer.OrdinalIgnoreCase))
                models.Add(ReMapApp.LootBinModelPath);
            if (world.Any(o => o.customType == "jump-pad") &&
                !models.Contains(ReMapApp.JumpPadModelPath, StringComparer.OrdinalIgnoreCase))
                models.Add(ReMapApp.JumpPadModelPath);
            if (world.Any(o => o.customType == "spawn-point") &&
                !models.Contains(ReMapApp.SpawnPointModelPath, StringComparer.OrdinalIgnoreCase))
                models.Add(ReMapApp.SpawnPointModelPath);
            if (world.Any(o => o.customType == "jump-tower"))
            {
                if (!models.Contains(ReMapApp.JumpTowerBaseModelPath, StringComparer.OrdinalIgnoreCase))
                    models.Add(ReMapApp.JumpTowerBaseModelPath);
                if (!models.Contains(ReMapApp.JumpTowerBalloonModelPath, StringComparer.OrdinalIgnoreCase))
                    models.Add(ReMapApp.JumpTowerBalloonModelPath);
            }
            Vector3 originOffset = OriginOffset(document);
            bool useOriginOffset = HasOriginOffset(originOffset);
            var shared = new StringBuilder();
            AppendRpakLoadRequests(shared, AdditionalRpaks(map, selectedRpaks));
            foreach (string model in models) shared.Append("\tPrecacheModel( $\"").Append(model).AppendLine("\" )");

            var server = new StringBuilder();
            server.Append("\tif ( GetMapName() != \"").Append(map).AppendLine("\" )");
            server.AppendLine("\t\treturn");
            server.AppendLine();
            AppendClear(server);
            if (useOriginOffset)
            {
                server.AppendLine();
                server.Append("\tvector originOffset = ").Append(Vector(ApexDisplay.Position(originOffset))).AppendLine();
            }
            if (serverObjects.Count > 0)
            {
                server.AppendLine();
                server.AppendLine("\t// Props");
                server.AppendLine("\tentity ent");
            }
            for (int i = 0; i < serverObjects.Count; i++) AppendObject(server, serverObjects[i], originOffset, useOriginOffset);
            AppendDoors(server, world, false, originOffset, useOriginOffset);
            AppendLootBins(server, world, false, originOffset, useOriginOffset);
            AppendJumpPads(server, world, false, originOffset, useOriginOffset);
            AppendSpawnPoints(server, world, false, originOffset, useOriginOffset);
            AppendTriggers(server, world, false, originOffset, useOriginOffset);
            AppendJumpTowers(server, world, false, originOffset, useOriginOffset);
            AppendCurvedZiplines(server, world, false, originOffset, useOriginOffset);
            AppendZiplines(server, world, false, originOffset, useOriginOffset);

            var client = new StringBuilder();
            client.Append("\tif ( GetMapName() != \"").Append(map).AppendLine("\" )");
            client.AppendLine("\t\treturn");
            client.AppendLine();
            AppendClear(client);
            if (useOriginOffset)
            {
                client.AppendLine();
                client.Append("\tvector originOffset = ").Append(Vector(ApexDisplay.Position(originOffset))).AppendLine();
            }
            if (clientObjects.Count > 0)
            {
                client.AppendLine();
                client.AppendLine("\t// Client-side props");
                client.AppendLine("\tentity ent");
            }
            foreach (var item in clientObjects)
            {
                client.Append("\tent = ReMap_CreateClientProp( $\"").Append(Model(item)).Append("\", ")
                    .Append(Position(item.position, originOffset, useOriginOffset)).Append(", ")
                    .Append(Vector(ApexDisplay.Angles(WorldView.ToVector(item.rotation)))).Append(", ")
                    .Append(Number(item.scale.x)).AppendLine(" )");
                foreach (var property in item.scriptProperties ?? new List<ScriptProperty>())
                    AppendProperty(client, "ent", property, "\t", true);
            }
            return new[]
            {
                new ReMapGameScriptEdit(SharedFileName, "Sh_ReMap_PrecacheMap", shared.ToString().TrimEnd()),
                new ReMapGameScriptEdit(ServerMapFileName, "Sv_ReMap_LoadMap", server.ToString().TrimEnd()),
                new ReMapGameScriptEdit(ClientMapFileName, "Cl_ReMap_LoadMap", client.ToString().TrimEnd())
            };
        }

        internal static IReadOnlyList<ReMapGameScriptEdit> ResetEdits(string gameTarget)
        {
            GameTargets.Normalize(gameTarget);
            return new[]
            {
                new ReMapGameScriptEdit(SharedFileName, "Sh_ReMap_PrecacheMap", "\tPrecacheModel( $\"mdl/dev/empty.rmdl\" )"),
                new ReMapGameScriptEdit(ServerMapFileName, "Sv_ReMap_LoadMap", ""),
                new ReMapGameScriptEdit(ClientMapFileName, "Cl_ReMap_LoadMap", "")
            };
        }

        private static string RenderEdits(string gameTarget, string sourceDescription, IReadOnlyList<ReMapGameScriptEdit> edits)
        {
            var code = new StringBuilder();
            AppendGeneratedHeader(code, gameTarget, sourceDescription);
            foreach (var edit in edits)
            {
                code.Append("// File: ").Append(DirectoryName).Append('/').AppendLine(edit.FileName);
                code.Append("global function ").AppendLine(edit.FunctionName);
                code.AppendLine();
                code.Append("void function ").Append(edit.FunctionName).Append("()");
                if (edit.Body.Length == 0) code.AppendLine(" {}");
                else
                {
                    code.AppendLine();
                    code.AppendLine("{");
                    code.AppendLine(edit.Body);
                    code.AppendLine("}");
                }
                code.AppendLine();
            }
            return code.ToString();
        }

        public static string GenerateLiveCommands(MapDocument document, IEnumerable<MapObject> worldObjects,
            IEnumerable<string> selectedRpaks = null)
        {
            EditingMap(document);
            string gameTarget = GameTargets.Normalize(document.gameTarget);
            var world = (worldObjects ?? throw new ArgumentNullException(nameof(worldObjects))).Where(o => o != null).ToList();
            var objects = Prepare(world).Where(o => !o.clientSide).ToList();
            Vector3 originOffset = OriginOffset(document);
            var result = new StringBuilder();
            foreach (string rpak in AdditionalRpaks(EditingMap(document), selectedRpaks))
                result.Append("pak_requestload ").AppendLine(rpak);
            result.Append("script Sh_ReMap_Clear()\n");
            for (int i = 0; i < objects.Count; i++)
                result.Append("script ").Append(CreateExpression(objects[i], originOffset, false)).AppendLine();
            AppendDoors(result, world, true, originOffset, false);
            AppendLootBins(result, world, true, originOffset, false);
            AppendJumpPads(result, world, true, originOffset, false);
            AppendSpawnPoints(result, world, true, originOffset, false);
            AppendJumpTowers(result, world, true, originOffset, false);
            AppendCurvedZiplines(result, world, true, originOffset, false);
            AppendZiplines(result, world, true, originOffset, false);
            return result.ToString();
        }

        internal static string[] AdditionalRpaks(string editingMap,
            IEnumerable<string> selectedRpaks)
        {
            string prefix = editingMap + ".rpak";
            string clientPerm = editingMap + "_client_perm.rpak";
            string clientTemp = editingMap + "_client_temp.rpak";
            var result = new List<string>();
            foreach (string source in selectedRpaks ?? Array.Empty<string>())
            {
                string rpak = (source ?? "").Trim();
                if (!Regex.IsMatch(rpak, @"^[A-Za-z0-9_()\-]+\.rpak$", RegexOptions.CultureInvariant))
                    throw new ArgumentException(L.F("#INVALID_RPAK_FILE_NAME_ARG0", rpak));
                if (string.Equals(rpak, prefix, StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(rpak, clientPerm, StringComparison.OrdinalIgnoreCase) ||
                    string.Equals(rpak, clientTemp, StringComparison.OrdinalIgnoreCase)) continue;
                if (!result.Contains(rpak, StringComparer.OrdinalIgnoreCase)) result.Add(rpak);
            }
            return result.ToArray();
        }

        private static void AppendRpakLoadRequests(StringBuilder code, IEnumerable<string> rpaks)
        {
            string[] archives = (rpaks ?? Array.Empty<string>()).ToArray();
            if (archives.Length == 0) return;
            code.AppendLine("#if SERVER");
            foreach (string rpak in archives)
                code.Append("\tServerCommand( \"pak_requestload ").Append(rpak).AppendLine("\" )");
            code.AppendLine("#elseif CLIENT");
            foreach (string rpak in archives)
                code.Append("\tClientCommand( \"pak_requestload ").Append(rpak).AppendLine("\" )");
            code.AppendLine("#endif");
            code.AppendLine();
        }

        private static void AppendClear(StringBuilder code)
        {
            code.AppendLine("\tSh_ReMap_Clear()");
        }

        private static string MapSourceDescription(MapDocument document)
        {
            string projectName = (document?.name ?? "").Replace('\r', ' ').Replace('\n', ' ').Trim();
            return projectName.Length == 0
                ? "Map source: current project in the ReMap app."
                : "Map source: ReMap project \"" + projectName + "\".";
        }

        private static void AppendGeneratedHeader(StringBuilder code, string gameTarget, string sourceDescription)
        {
            code.Append("// Generated by ReMap for ").Append(GameTargets.DisplayName(gameTarget)).AppendLine(".");
            code.Append("// ").AppendLine(sourceDescription);
            code.AppendLine("// ReMap only replaces the named function bodies in the installed scripts.");
            code.AppendLine("// Original ReMap by Zee (@AyeZeeBB / zee_x64) and Julefox (@Julefox_ / julefox).");
            code.AppendLine("// Standalone ReMap rewrite created and maintained by Julefox.");
            code.AppendLine("// Made with love for the Apex modding community. <3");
            code.AppendLine("// Built on the Apex modding foundation created by Mauler125: https://github.com/Mauler125/r5sdk");
            code.AppendLine();
        }

        private static string EditingMap(MapDocument document)
        {
            if (document == null) throw new ArgumentNullException(nameof(document));
            string map = (document.editingMap ?? "").Trim();
            if (!map.StartsWith("mp_", StringComparison.Ordinal) || map.Length > 128 || map.Any(c =>
                    !((c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9') || c == '_')))
                throw new ArgumentException(L.T("#SELECT_EDITED_APEX_MAP_BUILDING"));
            return map;
        }

        private static List<MapObject> Prepare(IEnumerable<MapObject> source)
        {
            var objects = (source ?? throw new ArgumentNullException(nameof(source))).Where(o => o != null && !o.isGroup && !o.disabled && string.IsNullOrEmpty(o.customType)).ToList();
            foreach (var item in objects)
            {
                Model(item);
                if (!Nearly(item.scale.x, item.scale.y) || !Nearly(item.scale.x, item.scale.z))
                    throw new ArgumentException(L.F("#ARG0_APEX_PROPS_SUPPORT_UNIFORM", item.displayName));
            }
            return objects;
        }

        private static string Model(MapObject item)
        {
            string model = (item.gameModelPath ?? "").Trim().Replace('\\', '/');
            if (!model.StartsWith("mdl/", StringComparison.OrdinalIgnoreCase) || !model.EndsWith(".rmdl", StringComparison.OrdinalIgnoreCase) ||
                model.IndexOfAny(new[] { '"', '\r', '\n' }) >= 0)
                throw new ArgumentException(L.F("#ARG0_NO_VALID_APEX_MODEL", item.displayName));
            return model;
        }

        private static void AppendObject(StringBuilder code, MapObject item, Vector3 originOffset, bool symbolicOffset)
        {
            const string variable = "ent";
            code.Append('\t').Append(variable).Append(" = ").Append(CreateExpression(item, originOffset, symbolicOffset)).AppendLine();
            foreach (var property in item.scriptProperties ?? new List<ScriptProperty>())
                AppendProperty(code, variable, property, "\t", true);
        }

        private static void AppendProperty(StringBuilder code, string variable, ScriptProperty property, string prefix, bool lineBreak = false)
        {
            code.Append(prefix).Append(variable).Append('.');
            if (!string.IsNullOrEmpty(property.scope)) code.Append(property.scope).Append('.');
            code.Append(property.name).Append(property.scope == "s" ? " <- " : " = ").Append(property.value);
            if (lineBreak) code.AppendLine();
        }

        private static string CreateExpression(MapObject item, Vector3 originOffset, bool symbolicOffset)
        {
            Vector3 angles = ApexDisplay.Angles(WorldView.ToVector(item.rotation));
            string common = "$\"" + Model(item) + "\", " + Position(item.position, originOffset, symbolicOffset) + ", " + Vector(angles);
            return "ReMap_CreateProp( " + common + ", " + (item.allowMantle ? "true" : "false") +
                ", " + Number(item.fadeDistance) + ", " + item.realmId.ToString(CultureInfo.InvariantCulture) +
                ", " + Number(item.scale.x) + " )";
        }

        private static void AppendZiplines(StringBuilder code, List<MapObject> world, bool live, Vector3 originOffset, bool symbolicOffset)
        {
            var byId = world.ToDictionary(o => o.id);
            var ziplines = world.Where(o => o.customType == "zipline").ToList();
            if (!live && ziplines.Count > 0) { code.AppendLine(); code.AppendLine("\t// Ziplines"); }
            foreach (var zipline in ziplines)
            {
                if (!byId.TryGetValue(zipline.ziplineStartId, out var start) || !byId.TryGetValue(zipline.ziplineEndId, out var end))
                    throw new ArgumentException(L.F("#ARG0_ZIPLINE_ENDPOINTS_MISSING", zipline.displayName));
                bool vertical = zipline.ziplineMode == "vertical";
                string startProfile = ReMapZiplineProfiles.Find(start.customProfile).ScriptConstant;
                string endProfile = ReMapZiplineProfiles.Find(end.customProfile).ScriptConstant;
                string expression = "ReMap_CreateZipline( " + Position(start.position, originOffset, symbolicOffset) + ", " + Vector(ApexDisplay.Angles(WorldView.ToVector(start.rotation))) +
                    ", " + Position(end.position, originOffset, symbolicOffset) + ", " + Vector(ApexDisplay.Angles(WorldView.ToVector(end.rotation))) + ", " +
                    startProfile + ", " + endProfile +
                    ", " + (vertical ? "true" : "false") + ", " + Number(zipline.ziplineWidth) + ", " + Number(zipline.ziplineSpeed) +
                    ", " + Number(start.ziplineArmHeight) + ", " + Number(end.ziplineArmHeight) +
                    ", " + (zipline.ziplinePushOffInDirectionX ? "true" : "false") + ", " + Number(zipline.ziplineLengthScale) +
                    ", " + Number(zipline.ziplinePushOffAngle) + ", " + Number(zipline.ziplineFadeDistance) +
                    ", " + Number(zipline.ziplineScale) + ", " + (zipline.ziplinePreserveVelocity ? "true" : "false") +
                    ", " + (zipline.ziplineDropToBottom ? "true" : "false") + ", " + Number(zipline.ziplineAutoDetachStart) +
                    ", " + Number(zipline.ziplineAutoDetachEnd) + ", " + (zipline.ziplineRestPoint ? "true" : "false") +
                    ", " + (zipline.ziplineDetachEndOnSpawn ? "true" : "false") +
                    ", " + (zipline.ziplineDetachEndOnUse ? "true" : "false") + " )";
                code.Append(live ? "script " : "\t").Append(expression).AppendLine();
            }
        }

        private static void AppendDoors(StringBuilder code, List<MapObject> world, bool live,
            Vector3 originOffset, bool symbolicOffset)
        {
            var doors = world.Where(o => o.customType == "door").ToList();
            if (!live && doors.Count > 0) { code.AppendLine(); code.AppendLine("\t// Doors"); }
            foreach (var door in doors)
            {
                var profile = ReMapDoorProfiles.Find(door.doorType);
                string expression = "ReMap_CreateDoor( " +
                    Position(door.position, originOffset, symbolicOffset) + ", " +
                    Vector(ApexDisplay.Angles(WorldView.ToVector(door.rotation))) + ", " +
                    profile.ScriptConstant + ", " +
                    (door.doorGold && profile.SupportsGold ? "true" : "false") + ", " +
                    (door.doorSpawnOpen ? "true" : "false") + " )";
                code.Append(live ? "script " : "\t").Append(expression).AppendLine();
            }
        }

        private static void AppendCurvedZiplines(StringBuilder code, List<MapObject> world, bool live,
            Vector3 originOffset, bool symbolicOffset)
        {
            var ziplines = world.Where(o => o.customType == "curved-zipline").ToList();
            if (!live && ziplines.Count > 0) { code.AppendLine(); code.AppendLine("\t// Curved ziplines"); }
            foreach (var zipline in ziplines)
            {
                var points = world.Where(o => o.parentId == zipline.id &&
                    o.customType == "curved-zipline-point")
                    .OrderBy(o => int.TryParse(o.customRole, out int index) ? index : int.MaxValue)
                    .ToList();
                if (points.Count < 2)
                    throw new ArgumentException(L.F("#ARG0_CURVED_ZIPLINE_POINTS_MISSING", zipline.displayName));
                string pointArray = "[ " + string.Join(", ", points.Select(point =>
                    Position(point.position, originOffset, symbolicOffset))) + " ]";
                string profileArray = "[ " + string.Join(", ", points.Select(point =>
                    ReMapZiplineProfiles.Find(point.customProfile).ScriptConstant)) + " ]";
                string angleArray = "[ " + string.Join(", ", points.Select(point =>
                    Vector(ApexDisplay.Angles(WorldView.ToVector(point.rotation))))) + " ]";
                string heightArray = "[ " + string.Join(", ", points.Select(point =>
                    Number(point.ziplineArmHeight))) + " ]";
                string expression = "ReMap_CreateCurvedZipline( " + pointArray + ", " +
                    zipline.curvedZiplineSegments.ToString(CultureInfo.InvariantCulture) + ", " +
                    profileArray + ", " + angleArray + ", " + heightArray + ", " +
                    Number(zipline.ziplineWidth) + ", " + Number(zipline.ziplineSpeed) + " )";
                code.Append(live ? "script " : "\t").Append(expression).AppendLine();
            }
        }

        private static void AppendLootBins(StringBuilder code, List<MapObject> world, bool live,
            Vector3 originOffset, bool symbolicOffset)
        {
            var lootBins = world.Where(o => o.customType == "loot-bin").ToList();
            if (!live && lootBins.Count > 0) { code.AppendLine(); code.AppendLine("\t// Loot bins"); }
            foreach (var lootBin in lootBins)
            {
                string expression = "ReMap_CreateLootBin( " +
                    Position(lootBin.position, originOffset, symbolicOffset) + ", " +
                    Vector(ApexDisplay.Angles(WorldView.ToVector(lootBin.rotation))) + ", " +
                    lootBin.lootBinSkin.ToString(CultureInfo.InvariantCulture) + " )";
                code.Append(live ? "script " : "\t").Append(expression).AppendLine();
            }
        }

        private static void AppendJumpPads(StringBuilder code, List<MapObject> world, bool live,
            Vector3 originOffset, bool symbolicOffset)
        {
            var jumpPads = world.Where(o => o.customType == "jump-pad").ToList();
            if (!live && jumpPads.Count > 0) { code.AppendLine(); code.AppendLine("\t// Jump pads"); }
            foreach (var jumpPad in jumpPads)
            {
                if (!Nearly(jumpPad.scale.x, jumpPad.scale.y) || !Nearly(jumpPad.scale.x, jumpPad.scale.z))
                    throw new ArgumentException(L.F("#ARG0_APEX_PROPS_SUPPORT_UNIFORM", jumpPad.displayName));
                string expression = "ReMap_CreateJumpPad( " +
                    Position(jumpPad.position, originOffset, symbolicOffset) + ", " +
                    Vector(ApexDisplay.Angles(WorldView.ToVector(jumpPad.rotation))) + ", " +
                    (jumpPad.allowMantle ? "true" : "false") + ", " +
                    Number(jumpPad.fadeDistance) + ", " +
                    jumpPad.realmId.ToString(CultureInfo.InvariantCulture) + ", " +
                    Number(jumpPad.scale.x) + ", " + Number(jumpPad.jumpPadLaunchVelocity) + ", " +
                    Number(jumpPad.jumpPadForwardScale) + ", " + Number(jumpPad.jumpPadRadius) + ", " +
                    (jumpPad.jumpPadDoubleJump ? "true" : "false") + " )";
                code.Append(live ? "script " : "\t").Append(expression).AppendLine();
            }
        }

        private static void AppendSpawnPoints(StringBuilder code, List<MapObject> world, bool live,
            Vector3 originOffset, bool symbolicOffset)
        {
            var spawnPoints = world.Where(o => o.customType == "spawn-point").ToList();
            if (!live && spawnPoints.Count > 0) { code.AppendLine(); code.AppendLine("\t// Player spawn points"); }
            foreach (var spawnPoint in spawnPoints)
            {
                string expression = "ReMap_CreateSpawnPoint( " +
                    Position(spawnPoint.position, originOffset, symbolicOffset) + ", " +
                    Vector(ApexDisplay.Angles(WorldView.ToVector(spawnPoint.rotation))) + ", " +
                    spawnPoint.spawnPointTeam.ToString(CultureInfo.InvariantCulture) + " )";
                code.Append(live ? "script " : "\t").Append(expression).AppendLine();
            }
        }

        private static void AppendTriggers(StringBuilder code, List<MapObject> world, bool live,
            Vector3 originOffset, bool symbolicOffset)
        {
            if (live) return;
            var triggers = world.Where(o => o.customType == "trigger").ToList();
            if (triggers.Count == 0) return;
            code.AppendLine(); code.AppendLine("\t// Triggers");
            for (int index = 0; index < triggers.Count; index++)
            {
                var trigger = triggers[index];
                string variable = "remapTrigger" + index.ToString(CultureInfo.InvariantCulture);
                code.Append("\tentity ").Append(variable).Append(" = ReMap_CreateTrigger( ")
                    .Append(Position(trigger.position, originOffset, symbolicOffset)).Append(", ")
                    .Append(Vector(ApexDisplay.Angles(WorldView.ToVector(trigger.rotation)))).Append(", ")
                    .Append(Number(trigger.triggerRadius)).Append(", ")
                    .Append(Number(trigger.triggerHalfHeight)).Append(", ")
                    .Append(trigger.triggerDebug ? "true" : "false").Append(", ")
                    .Append(trigger.realmId.ToString(CultureInfo.InvariantCulture)).AppendLine(" )");
                AppendTriggerCallback(code, variable, "SetEnterCallback", trigger.triggerEnterCallback);
                AppendTriggerCallback(code, variable, "SetLeaveCallback", trigger.triggerLeaveCallback);
                code.Append("\tDispatchSpawn( ").Append(variable).AppendLine(" )");
            }
        }

        private static void AppendJumpTowers(StringBuilder code, List<MapObject> world, bool live,
            Vector3 originOffset, bool symbolicOffset)
        {
            var towers = world.Where(o => o.customType == "jump-tower").ToList();
            if (!live && towers.Count > 0) { code.AppendLine(); code.AppendLine("\t// Jump towers"); }
            foreach (var tower in towers)
            {
                string expression = "ReMap_CreateJumpTower( " +
                    Position(tower.position, originOffset, symbolicOffset) + ", " +
                    Vector(ApexDisplay.Angles(WorldView.ToVector(tower.rotation))) + ", " +
                    Number(tower.jumpTowerHeight) + " )";
                code.Append(live ? "script " : "\t").Append(expression).AppendLine();
            }
        }

        private static void AppendTriggerCallback(StringBuilder code, string variable,
            string setter, string callback)
        {
            callback = (callback ?? "").Replace("\r\n", "\n").Replace('\r', '\n');
            if (string.IsNullOrWhiteSpace(callback)) return;
            code.Append('\t').Append(variable).Append('.').Append(setter)
                .AppendLine("( void function( entity trigger, entity ent )");
            code.AppendLine("\t{");
            foreach (string line in callback.Split('\n')) code.Append("\t\t").AppendLine(line);
            code.AppendLine("\t} )");
        }

        private static Vector3 OriginOffset(MapDocument document)
        {
            if (!document.originOffset.IsFinite || !ApexCoordinates.ContainsUnity(document.originOffset))
                throw new ArgumentException(L.T("#SCENE") + " : " + ApexCoordinates.LimitMessage);
            return WorldView.ToVector(document.originOffset);
        }

        private static bool HasOriginOffset(Vector3 value) => value.x != 0f || value.y != 0f || value.z != 0f;

        private static string Position(Float3 localPosition, Vector3 originOffset, bool symbolicOffset)
        {
            Vector3 local = WorldView.ToVector(localPosition);
            Vector3 game = local + originOffset;
            if (!ApexCoordinates.ContainsUnity(WorldView.ToData(game))) throw new ArgumentException(ApexCoordinates.LimitMessage);
            return Vector(ApexDisplay.Position(symbolicOffset ? local : game)) + (symbolicOffset ? " + originOffset" : "");
        }

        private static string Vector(Vector3 value) => "<" + Number(value.x) + ", " + Number(value.y) + ", " + Number(value.z) + ">";
        private static string Number(float value)
        {
            double rounded = Math.Round(value, 4, MidpointRounding.AwayFromZero);
            if (Math.Abs(rounded) < 0.00005) rounded = 0;
            return rounded.ToString("0.####", CultureInfo.InvariantCulture);
        }
        private static bool Nearly(float a, float b) => Math.Abs(a - b) <= Math.Max(0.0001f, Math.Max(Math.Abs(a), Math.Abs(b)) * 0.0001f);
    }

    internal sealed class ReMapGameScriptEdit
    {
        internal string FileName { get; }
        internal string FunctionName { get; }
        internal string Body { get; }

        internal ReMapGameScriptEdit(string fileName, string functionName, string body)
        {
            FileName = fileName;
            FunctionName = functionName;
            Body = (body ?? "").Replace("\r\n", "\n").TrimEnd();
        }

    }

    public static class ReMapGameScriptInstaller
    {
        private static readonly string[] ServerFileNames = { "sv_remap_objects.nut", "sv_remap_ziplines.nut", ReMapGameScript.ServerMapFileName, ReMapGameScript.SharedFileName };
        private static readonly string[] ClientFileNames = { "cl_remap_objects.nut", ReMapGameScript.ClientMapFileName, ReMapGameScript.SharedFileName };

        public static string EnsureInstalled(string platformDirectory, string gameTarget)
        {
            gameTarget = GameTargets.Normalize(gameTarget);
            string platform = (platformDirectory ?? "").Trim();
            if (platform.Length == 0) throw new DirectoryNotFoundException(L.T("#CONFIGURE_PLATFORM_FOLDER_SETTINGS_FIRST"));
            string scripts = Path.Combine(Path.GetFullPath(platform), "scripts", "vscripts");
            string remap = Path.Combine(scripts, ReMapGameScript.DirectoryName);
            var allFiles = ServerFileNames.Concat(ClientFileNames).Distinct(StringComparer.OrdinalIgnoreCase).ToArray();
            foreach (string fileName in allFiles)
            {
                string entry = ReMapGameScript.DirectoryName + "/" + fileName;
                string runtime = Path.Combine(remap, fileName);
                if (!File.Exists(runtime))
                    throw new FileNotFoundException(L.F("#ARG0_PLATFORM_CONTAIN_REQUIRED_ARG1", GameTargets.DisplayName(gameTarget), entry), runtime);
            }

            string initName = gameTarget == GameTargets.R5Flowstate ? "_sh_init.gnut" : "sh_init.gnut";
            string init = Path.Combine(scripts, initName);
            if (!File.Exists(init) || !File.ReadAllText(init).Contains("Sh_ReMap_Init()"))
                throw new InvalidDataException(L.F("#REMAP_INIT_MISSING", initName));

            return remap;
        }

        public static string Write(string platformDirectory, MapDocument document,
            IEnumerable<MapObject> worldObjects, IEnumerable<string> selectedRpaks = null)
        {
            if (document == null) throw new ArgumentNullException(nameof(document));
            return Apply(platformDirectory, document.gameTarget,
                ReMapGameScript.BuildEdits(document, worldObjects, selectedRpaks), true);
        }

        public static string Reset(string platformDirectory, string gameTarget)
        {
            return Apply(platformDirectory, gameTarget, ReMapGameScript.ResetEdits(gameTarget), false);
        }

        private static string Apply(string platformDirectory, string gameTarget, IReadOnlyList<ReMapGameScriptEdit> edits, bool loadMap)
        {
            gameTarget = GameTargets.Normalize(gameTarget);
            string remap = EnsureInstalled(platformDirectory, gameTarget);
            var changed = new List<KeyValuePair<string, string>>();
            foreach (var edit in edits)
            {
                string path = Path.Combine(remap, edit.FileName);
                string content = File.ReadAllText(path);
                content = ReplaceFunctionBody(content, edit.FunctionName, edit.Body, path);
                if (edit.FileName == ReMapGameScript.SharedFileName)
                    content = SetLoadMap(content, loadMap, path);
                changed.Add(new KeyValuePair<string, string>(path, content));
            }
            foreach (var file in changed)
            {
                BackupOnce(file.Key);
                File.WriteAllText(file.Key, file.Value, new UTF8Encoding(false));
            }
            return remap;
        }

        private static string ReplaceFunctionBody(string source, string functionName, string body, string path)
        {
            var matches = Regex.Matches(source, @"(?m)^(?<indent>[ \t]*)void\s+function\s+" + Regex.Escape(functionName) + @"\s*\(\s*\)\s*\{");
            if (matches.Count != 1)
                throw new InvalidDataException(path + " must contain exactly one " + functionName + "() function.");
            Match match = matches[0];
            int open = match.Index + match.Value.LastIndexOf('{');
            int close = FindClosingBrace(source, open, path, functionName);
            string newline = source.Contains("\r\n") ? "\r\n" : "\n";
            string indent = match.Groups["indent"].Value;
            string normalized = (body ?? "").Replace("\r\n", "\n").TrimEnd();
            string signature = indent + "void function " + functionName + "()";
            string replacement;
            if (normalized.Length == 0) replacement = signature + " {}";
            else
            {
                string formatted = string.Join(newline, normalized.Split('\n').Select(line => indent + line));
                replacement = signature + newline + indent + "{" + newline + formatted + newline + indent + "}";
            }
            return source.Substring(0, match.Index) + replacement + source.Substring(close + 1);
        }

        private static int FindClosingBrace(string source, int openingBrace, string path, string functionName)
        {
            int depth = 0;
            bool lineComment = false, blockComment = false, escaped = false;
            char quote = '\0';
            for (int i = openingBrace; i < source.Length; i++)
            {
                char current = source[i];
                char next = i + 1 < source.Length ? source[i + 1] : '\0';
                if (lineComment) { if (current == '\n') lineComment = false; continue; }
                if (blockComment) { if (current == '*' && next == '/') { blockComment = false; i++; } continue; }
                if (quote != '\0')
                {
                    if (escaped) { escaped = false; continue; }
                    if (current == '\\') { escaped = true; continue; }
                    if (current == quote) quote = '\0';
                    continue;
                }
                if (current == '/' && next == '/') { lineComment = true; i++; continue; }
                if (current == '/' && next == '*') { blockComment = true; i++; continue; }
                if (current == '"' || current == '\'') { quote = current; continue; }
                if (current == '{') depth++;
                else if (current == '}' && --depth == 0) return i;
            }
            throw new InvalidDataException(path + " contains an unclosed " + functionName + "() function.");
        }

        private static string SetLoadMap(string source, bool enabled, string path)
        {
            var matches = Regex.Matches(source, @"(?m)^(?<prefix>[ \t]*global\s+const\s+bool\s+REMAP_LOAD_MAP\s*=\s*)(?:true|false)(?<suffix>[ \t]*)$");
            if (matches.Count != 1)
                throw new InvalidDataException(path + " must contain exactly one REMAP_LOAD_MAP boolean constant.");
            Match match = matches[0];
            string replacement = match.Groups["prefix"].Value + (enabled ? "true" : "false") + match.Groups["suffix"].Value;
            return source.Substring(0, match.Index) + replacement + source.Substring(match.Index + match.Length);
        }

        private static void BackupOnce(string path)
        {
            string backup = path + ".remap.bak";
            if (!File.Exists(backup)) File.Copy(path, backup);
        }
    }

    internal static class ReMapNetConsole
    {
        internal static int Send(string gameTarget, string platformDirectory, string address, string key, string password, IEnumerable<string> sourceCommands)
        {
            var commands = (sourceCommands ?? Enumerable.Empty<string>()).SelectMany(command => (command ?? "").Split(new[] { "\r\n", "\n" }, StringSplitOptions.RemoveEmptyEntries)).Select(command => command.Trim()).Where(command => command.Length > 0).ToArray();
            if (commands.Length == 0) throw new ArgumentException(L.T("#ENTER_COMMAND_SEND"));
            key = (key ?? "").Trim(); password = password ?? "";
            if (GameTargets.Normalize(gameTarget) == GameTargets.R5Flowstate && key.Length == 0 && password.Length == 0)
                return ReMapLiveBridge.Send(commands);
            if (key.Length == 0 || password.Length == 0)
                throw new InvalidOperationException(L.T("#CONFIGURE_RCON_AES_KEY_PASSWORD"));

            string platform = (platformDirectory ?? "").Trim();
            if (string.IsNullOrWhiteSpace(platform)) throw new DirectoryNotFoundException(L.T("#CONFIGURE_PLATFORM_FOLDER_SETTINGS_FIRST"));
            string netcon = Path.GetFullPath(Path.Combine(platform, "..", "bin", "netcon.exe"));
            if (!File.Exists(netcon)) throw new FileNotFoundException(L.T("#R5RELOADED_NETCON_EXE_FOUND_NEXT"), netcon);
            address = (address ?? "").Trim();
            if (address.Length == 0 || address.Length > 128 || address.Any(c => !(char.IsLetterOrDigit(c) || "[]:.-_%".Contains(c))))
                throw new ArgumentException(L.T("#ENTER_VALID_RCON_SERVER_ADDRESS"));
            byte[] decoded;
            try { decoded = Convert.FromBase64String(key); }
            catch (FormatException) { throw new ArgumentException(L.T("#RCON_AES_KEY_VALID_BASE64")); }
            if (decoded.Length != 16) throw new ArgumentException(L.T("#RCON_AES_KEY_CONTAIN_EXACTLY"));
            if (string.IsNullOrEmpty(password) || password.IndexOfAny(new[] { '\r', '\n' }) >= 0)
                throw new ArgumentException(L.T("#CONFIGURE_NON_EMPTY_RCON_PASSWORD"));
            var output = new StringBuilder(); object outputLock = new object();
            using (var process = new System.Diagnostics.Process())
            {
                process.StartInfo = new System.Diagnostics.ProcessStartInfo
                {
                    FileName = netcon,
                    Arguments = QuoteArgument(address) + " " + QuoteArgument(key),
                    UseShellExecute = false,
                    CreateNoWindow = true,
                    RedirectStandardInput = true,
                    RedirectStandardOutput = true,
                    RedirectStandardError = true
                };
                process.OutputDataReceived += (_, e) => { if (e.Data != null) lock (outputLock) output.AppendLine(e.Data); };
                process.ErrorDataReceived += (_, e) => { if (e.Data != null) lock (outputLock) output.AppendLine(e.Data); };
                if (!process.Start()) throw new InvalidOperationException(L.T("#COULD_START_R5RELOADED_NETCON_EXE"));
                process.BeginOutputReadLine(); process.BeginErrorReadLine();
                process.StandardInput.WriteLine("PASS " + password);
                foreach (string command in commands) process.StandardInput.WriteLine(command);
                process.StandardInput.Close();
                int timeout = Math.Min(45000, 10000 + commands.Length * 15);
                if (!process.WaitForExit(timeout))
                {
                    try { process.Kill(); } catch { }
                    throw new TimeoutException(L.T("#LIVE_GAME_CONNECTION_DID_FINISH"));
                }
                process.WaitForExit();
                string transcript; lock (outputLock) transcript = output.ToString();
                if (process.ExitCode != 0 || transcript.IndexOf("Authentication failed", StringComparison.OrdinalIgnoreCase) >= 0 || transcript.IndexOf("Failed to authenticate", StringComparison.OrdinalIgnoreCase) >= 0)
                    throw new InvalidOperationException(L.T("#RCON_REJECTED_CONNECTION_CHECK_ADDRESS"));
            }
            return commands.Length;
        }

        private static string QuoteArgument(string value) => "\"" + value.Replace("\"", "\\\"") + "\"";
    }

    public sealed partial class ReMapApp
    {
        private VisualElement codeWindow;
        private ScrollView codePreviewScroll;
        private Label codePreview;
        private VisualElement liveWindow;
        private TextField liveCommand;
        private Label liveConnectionStatus;
        private Button liveSendButton, liveRebuildButton;
        private bool liveSending;
        private float codePreviewWidth = 720, codePreviewHeight = 520;
        private sealed class ScriptPropertyPreset
        {
            internal readonly string Label, Scope, Name, Value;
            internal ScriptPropertyPreset(string label, string scope, string name, string value)
            {
                Label = label; Scope = scope; Name = name; Value = value;
            }
            internal ScriptProperty Create() => new ScriptProperty { scope = Scope, name = Name, value = Value };
        }

        private static readonly ScriptPropertyPreset[] ScriptPropertyPresets =
        {
            new ScriptPropertyPreset("#SOLID_COLLISION", "kv", "solid", "6"),
            new ScriptPropertyPreset("#NO_DISTANCE_FADE", "kv", "fadedist", "-1"),
            new ScriptPropertyPreset("#DISABLE_SHADOWS", "kv", "disableshadows", "1"),
            new ScriptPropertyPreset("#RENDER_COLOR", "kv", "rendercolor", "\"255 255 255\""),
            new ScriptPropertyPreset("#RENDER_AMOUNT", "kv", "renderamt", "255"),
            new ScriptPropertyPreset("#RENDER_MODE", "kv", "rendermode", "0"),
            new ScriptPropertyPreset("#PREVENT_STICKY_ENTITIES", "e", "preventStickyEnts", "true"),
            new ScriptPropertyPreset("#DESTROY_OUT_BOUNDS", "e", "destroyOutOfBounds", "true"),
            new ScriptPropertyPreset("#BURN", "e", "canBurn", "true"),
            new ScriptPropertyPreset("#BLOCKS_THERMITE", "e", "blocksThermite", "true"),
            new ScriptPropertyPreset("#IGNORE_JUMP_PADS", "e", "ignoreJumpPad", "true"),
            new ScriptPropertyPreset("#IGNORE_PING_TRACE", "e", "ignorePingTrace", "true"),
            new ScriptPropertyPreset("#CUSTOM_SCRIPT_VALUE", "s", "remapValue", "null")
        };
        private static readonly List<string> ScriptPropertyScopes = new List<string> { ".", ".kv", ".e", ".s" };

        private static List<ScriptPropertyPreset> PropertyPresets(string scope, bool clientSide = false) =>
            ScriptPropertyPresets.Where(p => p.Scope == scope && !(clientSide && scope == "e")).ToList();

        private static string PropertyChoice(ScriptPropertyPreset preset) =>
            preset.Name + " · " + L.T(preset.Label);

        private static List<string> PropertyChoices(string scope, bool clientSide = false)
        {
            var choices = PropertyPresets(scope, clientSide).Select(PropertyChoice).ToList();
            choices.Add(L.T("#MANUAL_FIELD"));
            return choices;
        }

        private static ScriptProperty ManualProperty(string scope)
        {
            switch (scope)
            {
                case "": return new ScriptProperty { scope = "", name = "customField", value = "null" };
                case "kv": return new ScriptProperty { scope = "kv", name = "customKey", value = "0" };
                case "e": return new ScriptProperty { scope = "e", name = "customField", value = "null" };
                default: return new ScriptProperty { scope = "s", name = "remapValue", value = "null" };
            }
        }

        private void BuildCodePreviewWindow()
        {
            codeWindow = new VisualElement { name = "game-code-window" }; codeWindow.AddToClassList("floating-window"); codeWindow.AddToClassList("code-window"); root.Add(codeWindow);
            var title = DockTitle(L.T("#GENERATED_GAME_CODE")); title.AddToClassList("floating-title"); codeWindow.Add(title); BindFloatingPanel(title, codeWindow);
            var refresh = Button("↻", RefreshCodePreview, "dock-tab-action"); refresh.tooltip = L.T("#REFRESH_CODE"); title.Add(refresh);
            var copy = Button("⧉", CopyPreviewCode, "dock-tab-action"); copy.tooltip = L.T("#COPY_CODE"); title.Add(copy);
            title.Add(Button("×", () => ShowCodePreview(false), "dock-close"));
            codePreviewScroll = new ScrollView(ScrollViewMode.Vertical) {
                name = "game-code-scroll",
                horizontalScrollerVisibility = ScrollerVisibility.Hidden,
                verticalScrollerVisibility = ScrollerVisibility.AlwaysVisible
            };
            codePreviewScroll.AddToClassList("code-preview");
            codePreview = new Label { name = "game-code-content", focusable = true };
            codePreview.selection.isSelectable = true;
            codePreview.AddToClassList("code-preview-content");
            codePreviewScroll.Add(codePreview); codeWindow.Add(codePreviewScroll);
            var resize = new Label("◢") { name = "resize-game-code", tooltip = L.T("#DRAG_RESIZE_DOUBLE_CLICK_DEFAULT") };
            resize.AddToClassList("code-resize-grip"); codeWindow.Add(resize); BindCodePreviewResize(resize);
            root.RegisterCallback<GeometryChangedEvent>(_ => { if (codeWindow.style.display.value == DisplayStyle.Flex) ClampCodePreviewWindow(); });
            codeWindow.style.display = DisplayStyle.None;
        }

        private void BuildLiveConsoleWindow()
        {
            liveWindow = new VisualElement { name = "live-game-window" }; liveWindow.AddToClassList("floating-window"); liveWindow.AddToClassList("live-window"); root.Add(liveWindow);
            var title = DockTitle(L.T("#LIVE_GAME")); title.AddToClassList("floating-title"); liveWindow.Add(title); BindFloatingPanel(title, liveWindow);
            title.Add(Button("×", () => ShowLiveConsole(false), "dock-close"));
            liveConnectionStatus = Label("", "live-connection-status"); liveWindow.Add(liveConnectionStatus);
            liveCommand = new TextField(L.T("#SERVER_COMMAND")) { name = "live-command", tooltip = L.T("#COMMAND_EXECUTED_RUNNING_SERVER_RCON") }; liveCommand.AddToClassList("live-command"); liveWindow.Add(liveCommand);
            var actions = new VisualElement(); actions.AddToClassList("live-actions"); liveWindow.Add(actions);
            liveSendButton = Button(L.T("#SEND_COMMAND"), () => SendLive(false)); actions.Add(liveSendButton);
            liveRebuildButton = Button(L.T("#REBUILD_MAP_NOW"), () => SendLive(true), "primary"); actions.Add(liveRebuildButton);
            liveWindow.Add(Label(L.T("#REBUILD_CLEARS_REMAP_PROPS_RECREATES"), "note"));
            liveWindow.style.display = DisplayStyle.None;
        }

        private void ShowLiveConsole(bool show = true)
        {
            if (liveWindow == null) return;
            liveWindow.style.display = show ? DisplayStyle.Flex : DisplayStyle.None;
            if (show)
            {
                string launchError = ActiveSceneLaunchError();
                bool launcherMode = snapshot.gameTarget == GameTargets.R5Flowstate && string.IsNullOrWhiteSpace(assetLibrary.Settings.rconKey) && string.IsNullOrEmpty(assetLibrary.Settings.rconPassword);
                string address = string.IsNullOrWhiteSpace(assetLibrary.Settings.rconAddress) ? "[::ffff:127.0.0.1]:37015" : assetLibrary.Settings.rconAddress;
                liveConnectionStatus.text = string.IsNullOrEmpty(launchError) ? (launcherMode ? L.T("#AUTOMATIC_LOCAL_CONNECTION_FLOWSTATE_LAUNCHER") : L.T("#RCON_TARGET") + address) : launchError;
                liveRebuildButton.SetEnabled(snapshot.objects.Count > 0 && string.IsNullOrEmpty(launchError));
                liveWindow.BringToFront(); liveCommand.Focus();
            }
        }

        private string ActiveSceneLaunchError()
        {
            if (snapshot == null || assetLibrary == null) return L.T("#NO_MAP_OPEN");
            string target = GameTargets.Normalize(snapshot.gameTarget);
            if (assetLibrary.TargetGame != target)
                return L.F("#PROJECT_CREATED_ARG0_BUT_ACTIVE", GameTargets.DisplayName(target), GameTargets.DisplayName(assetLibrary.TargetGame));
            string[] missing = RsxAssetLibrary.FindMissingTargets(snapshot.targetMaps, assetLibrary.Maps.Select(map => map.Id));
            return missing.Length == 0 ? "" : L.F("#SCENE_CANNOT_STARTED_ARG0_MISSING", GameTargets.DisplayName(target), string.Join(", ", missing));
        }

        private async void SendLive(bool rebuild)
        {
            if (liveSending) return;
            string platform = assetLibrary.PlatformDirectory.Trim();
            string[] commands;
            try
            {
                CommitInspectorEdit();
                if (rebuild)
                {
                    string launchError = ActiveSceneLaunchError();
                    if (!string.IsNullOrEmpty(launchError)) throw new InvalidOperationException(launchError);
                }
                string text = rebuild ? ReMapGameScript.GenerateLiveCommands(snapshot,
                    world.GenerationObjects(snapshot), SelectedScriptRpaks()) : liveCommand.value;
                commands = (text ?? "").Split(new[] { "\r\n", "\n" }, StringSplitOptions.RemoveEmptyEntries);
                if (commands.Length == 0) throw new ArgumentException(L.T("#ENTER_COMMAND_SEND"));
            }
            catch (Exception ex) { SetStatus(ex.Message); liveConnectionStatus.text = ex.Message; return; }
            liveSending = true; liveSendButton.SetEnabled(false); liveRebuildButton.SetEnabled(false);
            liveConnectionStatus.text = rebuild ? L.T("#REBUILDING_MAP_RUNNING_GAME") : L.T("#SENDING_COMMAND");
            try
            {
                int count = await System.Threading.Tasks.Task.Run(() => ReMapNetConsole.Send(snapshot.gameTarget, platform, assetLibrary.Settings.rconAddress, assetLibrary.Settings.rconKey, assetLibrary.Settings.rconPassword, commands));
                string message = rebuild ? L.F("#LIVE_MAP_REBUILT_ARG0_COMMANDS", count) : L.F("#ARG0_COMMAND_S_SENT_RUNNING", count);
                liveConnectionStatus.text = message; SetStatus(message);
                if (!rebuild) liveCommand.value = "";
            }
            catch (Exception ex) { liveConnectionStatus.text = ex.Message; SetStatus(ex.Message); Debug.LogException(ex); }
            finally { liveSending = false; liveSendButton.SetEnabled(true); liveRebuildButton.SetEnabled(snapshot?.objects.Count > 0 && string.IsNullOrEmpty(ActiveSceneLaunchError())); }
        }

        private void ShowCodePreview(bool show = true)
        {
            if (codeWindow == null) return;
            if (show)
            {
                float maxWidth = Mathf.Max(1, root.resolvedStyle.width - 16), maxHeight = Mathf.Max(1, root.resolvedStyle.height - 16);
                float width = Mathf.Clamp(codePreviewWidth, Mathf.Min(380, maxWidth), maxWidth);
                float height = Mathf.Clamp(codePreviewHeight, Mathf.Min(260, maxHeight), maxHeight);
                codeWindow.style.width = width; codeWindow.style.height = height;
                ClampCodePreviewWindow(width, height);
                RefreshCodePreview(); codeWindow.style.display = DisplayStyle.Flex; codeWindow.BringToFront();
            }
            else codeWindow.style.display = DisplayStyle.None;
        }

        private void ClampCodePreviewWindow(float width = -1, float height = -1)
        {
            if (codeWindow == null || root == null) return;
            float rootWidth = root.resolvedStyle.width, rootHeight = root.resolvedStyle.height;
            if (width < 0) width = codeWindow.resolvedStyle.width;
            if (height < 0) height = codeWindow.resolvedStyle.height;
            if (!float.IsFinite(rootWidth) || !float.IsFinite(rootHeight) || !float.IsFinite(width) || !float.IsFinite(height)) return;
            float maxWidth = Mathf.Max(1, rootWidth - 16), maxHeight = Mathf.Max(1, rootHeight - 16);
            width = Mathf.Clamp(width, Mathf.Min(380, maxWidth), maxWidth);
            height = Mathf.Clamp(height, Mathf.Min(260, maxHeight), maxHeight);
            codeWindow.style.width = width; codeWindow.style.height = height;
            float left = codeWindow.resolvedStyle.left, top = codeWindow.resolvedStyle.top;
            if (!float.IsFinite(left)) left = (rootWidth - width) * .5f;
            if (!float.IsFinite(top)) top = (rootHeight - height) * .5f;
            codeWindow.style.left = Mathf.Clamp(left, 8, Mathf.Max(8, rootWidth - width - 8));
            codeWindow.style.top = Mathf.Clamp(top, 8, Mathf.Max(8, rootHeight - height - 8));
        }

        private void BindCodePreviewResize(VisualElement handle)
        {
            Vector2 pointerStart = default, sizeStart = default; int pointerId = -1; bool resizing = false;
            handle.RegisterCallback<PointerDownEvent>(e =>
            {
                if (e.button != 0) return;
                if (e.clickCount == 2) { ResizeCodePreviewWindow(720, 520); e.StopPropagation(); return; }
                pointerStart = e.position; sizeStart = codeWindow.worldBound.size; pointerId = e.pointerId; resizing = true;
                handle.CapturePointer(pointerId); handle.AddToClassList("resizing"); codeWindow.BringToFront(); e.StopPropagation();
            });
            handle.RegisterCallback<PointerMoveEvent>(e =>
            {
                if (!resizing || e.pointerId != pointerId) return;
                Vector2 delta = (Vector2)e.position - pointerStart;
                ResizeCodePreviewWindow(sizeStart.x + delta.x, sizeStart.y + delta.y); e.StopPropagation();
            });
            void End()
            {
                if (!resizing) return; resizing = false; handle.RemoveFromClassList("resizing");
                if (handle.HasPointerCapture(pointerId)) handle.ReleasePointer(pointerId);
                pointerId = -1;
            }
            handle.RegisterCallback<PointerUpEvent>(e => { if (e.pointerId == pointerId) { End(); e.StopPropagation(); } });
            handle.RegisterCallback<PointerCaptureOutEvent>(_ => End());
        }

        private void ResizeCodePreviewWindow(float width, float height)
        {
            float rootWidth = root.resolvedStyle.width, rootHeight = root.resolvedStyle.height;
            float left = Mathf.Max(8, codeWindow.resolvedStyle.left), top = Mathf.Max(8, codeWindow.resolvedStyle.top);
            float maxWidth = Mathf.Max(1, rootWidth - left - 8), maxHeight = Mathf.Max(1, rootHeight - top - 8);
            width = Mathf.Clamp(width, Mathf.Min(380, maxWidth), maxWidth);
            height = Mathf.Clamp(height, Mathf.Min(260, maxHeight), maxHeight);
            codePreviewWidth = width; codePreviewHeight = height;
            codeWindow.style.width = width; codeWindow.style.height = height;
            ClampCodePreviewWindow(width, height);
        }

        private void RefreshCodePreview()
        {
            CommitInspectorEdit();
            try { codePreview.text = ReMapGameScript.Generate(snapshot,
                world.GenerationObjects(snapshot), SelectedScriptRpaks()); }
            catch (Exception ex) { codePreview.text = "// " + ex.Message; }
            codePreviewScroll.scrollOffset = Vector2.zero;
        }

        private void CopyPreviewCode()
        {
            RefreshCodePreview(); GUIUtility.systemCopyBuffer = codePreview.text;
            SetStatus(L.T("#GENERATED_GAME_CODE_COPIED"));
        }

        private bool PointerOverFloatingPanel(Vector2 position) =>
            toolsOpen && toolsWindow?.style.display.value == DisplayStyle.Flex && toolsWindow.worldBound.Contains(position) ||
            codeWindow?.style.display.value == DisplayStyle.Flex && codeWindow.worldBound.Contains(position) ||
            liveWindow?.style.display.value == DisplayStyle.Flex && liveWindow.worldBound.Contains(position);

        private void BuildGameScript()
        {
            CommitInspectorEdit();
            string path = ReMapGameScriptInstaller.Write(assetLibrary.PlatformDirectory, snapshot,
                world.GenerationObjects(snapshot), SelectedScriptRpaks());
            SetStatus(L.T("#GAME_SCRIPT_BUILT") + path);
        }

        private void ResetGameScript()
        {
            string path = ReMapGameScriptInstaller.Reset(assetLibrary.PlatformDirectory, snapshot.gameTarget);
            SetStatus(L.T("#INSTALLED_REMAP_SCRIPT_RESET_BUILD"));
        }

        private void CopyLiveCommands()
        {
            CommitInspectorEdit();
            string commands = ReMapGameScript.GenerateLiveCommands(snapshot,
                world.GenerationObjects(snapshot), SelectedScriptRpaks());
            GUIUtility.systemCopyBuffer = commands;
            SetStatus(L.F("#ARG0_LIVE_COMMANDS_COPIED_PASTE", commands.Count(c => c == '\n')));
        }

        private string[] SelectedScriptRpaks() => assetLibrary?.SelectedMapArchives(Targets) ??
            Array.Empty<string>();

        private void BuildClassicPropSettings(MapObject item, VisualElement section)
        {
            var settings = new VisualElement { name = "classic-prop-settings" };
            settings.AddToClassList("inspector-subsection");
            var title = Label(L.T("#CLASSIC_PROP_SETTINGS"), "inspector-subsection-title");
            title.tooltip = L.T("#CLASSIC_PROP_SETTINGS_HELP"); settings.Add(title);

            var mantle = CompactInspectorField(new Toggle(L.T("#ALLOW_MANTLE")) { value = item.allowMantle });
            var fade = CompactInspectorField(new FloatField(L.T("#FADE_DISTANCE_APEX_U")) { value = item.fadeDistance, isDelayed = true });
            var realm = CompactInspectorField(new IntegerField(L.T("#REALM_ID")) { value = item.realmId, isDelayed = true });
            var client = CompactInspectorField(new Toggle(L.T("#CLIENT_SIDE_PROP")) { value = item.clientSide });
            settings.Add(mantle); settings.Add(fade); settings.Add(realm); settings.Add(client);

            mantle.RegisterValueChangedCallback(change => ChangeClassicProp(item.id, prop => prop.allowMantle = change.newValue));
            fade.RegisterValueChangedCallback(change =>
            {
                float value = float.IsFinite(change.newValue) ? Mathf.Max(-1f, change.newValue) : 50000f;
                if (!Mathf.Approximately(value, change.newValue)) fade.SetValueWithoutNotify(value);
                ChangeClassicProp(item.id, prop => prop.fadeDistance = value);
            });
            realm.RegisterValueChangedCallback(change =>
            {
                int value = Math.Max(-1, change.newValue);
                if (value != change.newValue) realm.SetValueWithoutNotify(value);
                ChangeClassicProp(item.id, prop => prop.realmId = value);
            });
            client.RegisterValueChangedCallback(change => ChangeClassicProp(item.id, prop => prop.clientSide = change.newValue));
            if (item.clientSide)
                settings.Add(Label(L.T("#CLIENT_PROP_CLASSIC_SETTINGS_IGNORED"), "inspector-inline-help"));
            section.Add(settings);
        }

        private void ChangeClassicProp(string id, Action<MapObject> change)
        {
            CommitInspectorEdit();
            session.Edit(document => change(document.objects.Find(candidate => candidate.id == id)));
            Refresh();
        }

        private void BuildScriptProperties(MapObject item, VisualElement section)
        {
            var properties = item.scriptProperties ?? new List<ScriptProperty>();
            var propertiesSection = new VisualElement { name = "script-properties" }; propertiesSection.AddToClassList("inspector-subsection");
            propertiesSection.tooltip = L.T("#CHOOSE_PROPERTY_FAMILY_COMPATIBLE_FIELD");
            var header = new VisualElement(); header.AddToClassList("script-properties-header");
            header.Add(Label(L.T("#SCRIPT_OPTIONS"), "script-properties-title"));
            header.Add(Label(properties.Count.ToString(CultureInfo.InvariantCulture), "script-properties-count"));
            propertiesSection.Add(header);

            var addCard = new VisualElement(); addCard.AddToClassList("script-property-add-card");
            var addRow = new VisualElement { name = "script-property-add" }; addRow.AddToClassList("script-property-add-controls");
            var addScope = new DropdownField(ScriptPropertyScopes, 1) { name = "script-property-add-scope", tooltip = L.T("#PROPERTY_FAMILY") };
            addScope.AddToClassList("script-property-scope");
            var addField = new DropdownField { name = "script-property-add-field", tooltip = L.T("#PROPERTY_FIELD") };
            addField.AddToClassList("script-property-field");
            void RefreshAddFields()
            {
                var choices = PropertyChoices(addScope.value.TrimStart('.'), item.clientSide);
                addField.choices = choices;
                addField.SetValueWithoutNotify(choices[0]);
            }
            addScope.RegisterValueChangedCallback(_ => RefreshAddFields());
            var add = Button("+", () =>
            {
                string selectedScope = addScope.value.TrimStart('.');
                var presets = PropertyPresets(selectedScope, item.clientSide);
                int selected = addField.choices.IndexOf(addField.value);
                var property = selected >= 0 && selected < presets.Count ? presets[selected].Create() : ManualProperty(selectedScope);
                ChangeScriptProperties(item.id, list => list.Add(property));
            });
            add.tooltip = L.T("#ADD_PROPERTY");
            add.AddToClassList("script-property-add-button"); add.AddToClassList("primary");
            addRow.Add(addScope); addRow.Add(addField); addRow.Add(add);
            addCard.Add(addRow); propertiesSection.Add(addCard); RefreshAddFields();

            for (int i = 0; i < properties.Count; i++)
            {
                int index = i;
                var property = properties[i];
                var card = new VisualElement(); card.AddToClassList("script-property-card");
                var row = new VisualElement(); row.AddToClassList("script-property-row");
                int scopeIndex = Math.Max(0, ScriptPropertyScopes.IndexOf("." + property.scope));
                var scope = new DropdownField(ScriptPropertyScopes, scopeIndex) { name = "script-property-scope", tooltip = L.T("#PROPERTY_FAMILY") };
                scope.AddToClassList("script-property-scope");
                var presets = PropertyPresets(property.scope, item.clientSide);
                var choices = PropertyChoices(property.scope, item.clientSide);
                int knownIndex = presets.FindIndex(p => p.Name == property.name);
                var field = new DropdownField(choices, knownIndex >= 0 ? knownIndex : choices.Count - 1) { name = "script-property-field", tooltip = L.T("#PROPERTY_FIELD") };
                field.AddToClassList("script-property-field");
                row.Add(scope); row.Add(field);
                var remove = Button("×", () => ChangeScriptProperties(item.id, list => list.RemoveAt(index)), "script-property-remove-button");
                remove.tooltip = L.T("#DELETE"); row.Add(remove);
                card.Add(row);
                var editorRow = new VisualElement(); editorRow.AddToClassList("script-property-editor-row");
                TextField name = null;
                if (knownIndex < 0)
                {
                    name = new TextField { value = property.name, isDelayed = true, tooltip = L.T("#FIELD_NAME") };
                    name.AddToClassList("script-property-name");
                    var nameControl = new VisualElement(); nameControl.AddToClassList("script-property-value-control"); nameControl.AddToClassList("script-property-name-control");
                    nameControl.Add(Label(L.T("#FIELD_NAME"), "script-property-control-label")); nameControl.Add(name); editorRow.Add(nameControl);
                    editorRow.Add(Label("=", "script-property-equals"));
                }
                var value = new TextField { value = property.value, isDelayed = true, tooltip = L.T("#SQUIRREL_VALUE") };
                value.AddToClassList("script-property-value");
                var valueControl = new VisualElement(); valueControl.AddToClassList("script-property-value-control"); valueControl.AddToClassList("script-property-value-entry-control");
                valueControl.Add(Label(L.T("#SQUIRREL_VALUE"), "script-property-control-label")); valueControl.Add(value); editorRow.Add(valueControl);
                card.Add(editorRow);
                scope.RegisterValueChangedCallback(e =>
                {
                    string selectedScope = e.newValue.TrimStart('.');
                    var replacement = PropertyPresets(selectedScope, item.clientSide).FirstOrDefault()?.Create() ?? ManualProperty(selectedScope);
                    ChangeScriptProperties(item.id, list => list[index] = replacement);
                });
                field.RegisterValueChangedCallback(e =>
                {
                    int selected = choices.IndexOf(e.newValue);
                    var replacement = selected >= 0 && selected < presets.Count ? presets[selected].Create() : ManualProperty(property.scope);
                    ChangeScriptProperties(item.id, list => list[index] = replacement);
                });
                if (name != null) name.RegisterValueChangedCallback(e => ChangeScriptProperties(item.id, list => list[index].name = e.newValue.Trim()));
                value.RegisterValueChangedCallback(e => ChangeScriptProperties(item.id, list => list[index].value = e.newValue.Trim()));
                propertiesSection.Add(card);
            }
            if (item.clientSide)
                propertiesSection.Add(Label(L.T("#CLIENT_E_FIELDS_MANUAL_ONLY"), "script-properties-help"));
            section.Add(propertiesSection);
        }

        private void ChangeScriptProperties(string id, Action<List<ScriptProperty>> change)
        {
            CommitInspectorEdit();
            session.Edit(doc =>
            {
                var target = doc.objects.Find(o => o.id == id);
                target.scriptProperties = target.scriptProperties ?? new List<ScriptProperty>();
                change(target.scriptProperties);
            });
            Refresh();
        }
    }
}
