// Generated by ReMap for R5Flowstate.
// Source code: https://github.com/ReMap
// Do not edit this file directly; rebuild it from the ReMap sources.

/*
 * ReMap game scripts
 *
 * Source lineage: rewritten from the active R5Reloaded ReMap implementation
 * and the legacy ReMap scripts.
 * Original ReMap: Zee (@AyeZeeBB on X, zee_x64 on Discord)
 * and Julefox (@Julefox_ on X, julefox on Discord).
 * This standalone ReMap rewrite was created and is maintained by Julefox.
 *
 * Made with love for the Apex modding community. <3
 * Built on the Apex modding foundation created by Amos (@AmosModz on X, amosmodz on Discord):
 * https://github.com/Mauler125/r5sdk
 */

global function ReMap_ClearClientProps
global function ReMap_CreateClientProp

struct
{
	array< entity > props
} file

void function ReMap_ClearClientProps()
{
	foreach ( entity prop in file.props )
	{
		if ( IsValid( prop ) )
			prop.Destroy()
	}

	file.props.clear()
}

entity function ReMap_CreateClientProp( asset model, vector origin, vector angles, float scale = 1.0 )
{
	entity prop = CreateClientSidePropDynamic( origin, angles, model )
	prop.SetModelScale( scale )
	file.props.append( prop )
	return prop
}
