// Generated by ReMap for R5Flowstate.
// Source code: https://github.com/ReMap
// Do not edit this file directly; rebuild it from the ReMap sources.

/*
 * ReMap game scripts
 *
 * Source lineage: rewritten from the active R5Reloaded ReMap implementation
 * and the legacy ReMap zipline scripts.
 * Original ReMap: Zee (@AyeZeeBB on X, zee_x64 on Discord)
 * and Julefox (@Julefox_ on X, julefox on Discord).
 * This standalone ReMap rewrite was created and is maintained by Julefox.
 *
 * Made with love for the Apex modding community. <3
 * Built on the Apex modding foundation created by Amos (@AmosModz on X, amosmodz on Discord):
 * https://github.com/Mauler125/r5sdk
 */

global function ReMap_PrecacheZiplines
global function ReMap_ClearZiplines
global function ReMap_CreateZipline

global const int REMAP_ZIPLINE_END_NONE = 0
global const int REMAP_ZIPLINE_END_ARM = 1
global const int REMAP_ZIPLINE_END_SUPPORT = 2

const asset REMAP_ZIPLINE_MODEL_ARM = $"mdl/industrial/zipline_arm.rmdl"
const asset REMAP_ZIPLINE_MODEL_SUPPORT = $"mdl/industrial/security_fence_post.rmdl"

struct
{
	array< entity > entities
} file

void function ReMap_PrecacheZiplines()
{
	PrecacheModel( REMAP_ZIPLINE_MODEL_ARM )
	PrecacheModel( REMAP_ZIPLINE_MODEL_SUPPORT )
}

void function ReMap_ClearZiplines()
{
	foreach ( entity ent in file.entities )
	{
		if ( IsValid( ent ) )
			ent.Destroy()
	}

	file.entities.clear()
}

void function ReMap_CreateZipline( vector startOrigin, vector startAngles, vector endOrigin, vector endAngles, int startProfile = REMAP_ZIPLINE_END_ARM, int endProfile = REMAP_ZIPLINE_END_ARM, bool vertical = false, float width = 2.0, float speedScale = 1.0, float startArmHeight = 180.0, float endArmHeight = 180.0, bool pushOffInDirectionX = false, float lengthScale = 1.0, float pushOffAngle = 0.0, float fadeDistance = -1.0, float ziplineScale = 1.0, bool preserveVelocity = false, bool dropToBottom = true, float startAutoDetachDistance = 100.0, float endAutoDetachDistance = 100.0, bool restPoint = false, bool detachEndOnSpawn = false, bool detachEndOnUse = false )
{
	if ( startOrigin == endOrigin )
		return

	vector startCableOrigin = ReMap_CreateZiplineEndModel( startProfile, startOrigin, startAngles, startArmHeight )
	vector endCableOrigin = ReMap_CreateZiplineEndModel( vertical ? REMAP_ZIPLINE_END_NONE : endProfile, endOrigin, endAngles, endArmHeight )
	vector startCableAngles = startAngles
	vector endCableAngles = endAngles

	if ( vertical )
	{
		endCableOrigin = <startCableOrigin.x, startCableOrigin.y, endCableOrigin.z>
		startCableAngles = <0.0, pushOffAngle, 0.0>
		endCableAngles = startCableAngles
	}
	else
	{
		startCableAngles = VectorToAngles( Normalize( endCableOrigin - startCableOrigin ) )
		endCableAngles = VectorToAngles( Normalize( startCableOrigin - endCableOrigin ) )
	}

	entity startPoint = CreateEntity( "zipline" )
	startPoint.kv.DetachEndOnSpawn = detachEndOnSpawn ? 1 : 0
	startPoint.kv.DetachEndOnUse = detachEndOnUse ? 1 : 0
	startPoint.kv.Material = "cable/zipline.vmt"
	startPoint.kv.scale = ziplineScale
	startPoint.kv.Width = width
	startPoint.kv.ZiplineAutoDetachDistance = startAutoDetachDistance
	startPoint.kv.ZiplineDropToBottom = dropToBottom ? 1 : 0
	startPoint.kv.ZiplineFadeDistance = fadeDistance
	startPoint.kv.ZiplineLengthScale = lengthScale
	startPoint.kv.ZiplinePreserveVelocity = preserveVelocity ? 1 : 0
	startPoint.kv.ZiplinePushOffInDirectionX = pushOffInDirectionX ? 1 : 0
	startPoint.kv.ZiplineSpeedScale = speedScale
	startPoint.kv.ZiplineVersion = 3
	startPoint.kv.ZiplineVertical = vertical
	if ( restPoint )
	{
		startPoint.kv._zipline_rest_point_0 = startCableOrigin.x + " " + startCableOrigin.y + " " + startCableOrigin.z
		startPoint.kv._zipline_rest_point_1 = endCableOrigin.x + " " + endCableOrigin.y + " " + endCableOrigin.z
	}
	startPoint.SetAngles( startCableAngles )
	startPoint.SetOrigin( startCableOrigin )

	entity endPoint = CreateEntity( "zipline_end" )
	endPoint.kv.ZiplineAutoDetachDistance = endAutoDetachDistance
	endPoint.kv.ZiplinePushOffInDirectionX = pushOffInDirectionX ? 1 : 0
	endPoint.SetAngles( endCableAngles )
	endPoint.SetOrigin( endCableOrigin )

	startPoint.LinkToEnt( endPoint )
	DispatchSpawn( startPoint )
	DispatchSpawn( endPoint )
	file.entities.append( startPoint )
	file.entities.append( endPoint )
}


vector function ReMap_CreateZiplineEndModel( int profile, vector origin, vector angles, float armHeight = 180.0 )
{
	vector armAngles = <angles.x, angles.y + 90.0, angles.z>
	if ( profile == REMAP_ZIPLINE_END_ARM )
	{
		ReMap_CreateProp( REMAP_ZIPLINE_MODEL_ARM, origin, armAngles )
		return origin + RotateVector( <-58, -2, -14>, angles )
	}
	else if ( profile == REMAP_ZIPLINE_END_SUPPORT )
	{
		ReMap_CreateProp( REMAP_ZIPLINE_MODEL_SUPPORT, origin, angles )
		vector armOrigin = origin + RotateVector( <4, -2.5, armHeight>, angles )
		ReMap_CreateProp( REMAP_ZIPLINE_MODEL_ARM, armOrigin, armAngles )
		return armOrigin + RotateVector( <-58, -2, -14>, angles )
	}

	return origin
}
