// Generated by ReMap for R5Flowstate.
// Source code: https://github.com/ReMap
// Do not edit this file directly; rebuild it from the ReMap sources.

/*
 * ReMap game scripts
 *
 * Source lineage: rewritten from the active R5Reloaded ReMap implementation
 * and the legacy ReMap scripts.
 * Original ReMap: Zee (@AyeZeeBB on X, zee_x64 on Discord)
 * and Julefox (@Julefox_ on X, julefox on Discord).
 * This standalone ReMap rewrite was created and is maintained by Julefox.
 *
 * Made with love for the Apex modding community. <3
 * Built on the Apex modding foundation created by Amos (@AmosModz on X, amosmodz on Discord):
 * https://github.com/Mauler125/r5sdk
 */

global function ReMap_ClearProps
global function ReMap_CreateProp
global function ReMap_CreateDoor
global function ReMap_CreateLootBin
global function ReMap_CreateJumpPad
global function ReMap_CreateSpawnPoint
global function ReMap_CreateTrigger
global function ReMap_CreateJumpTower
global function ReMap_CreateWeaponRack
global function ReMap_CreateRespawnHeal
global function ReMap_CreateButton
global function ReMap_CreateTeleportButton
global function ReMap_CreateSpeedBoost
global function ReMap_CreateBubbleShield
global function ReMap_CreateAnimatedCamera
global function ReMap_CreateSound

global const int REMAP_DOOR_SINGLE = 0
global const int REMAP_DOOR_DOUBLE = 1
global const int REMAP_DOOR_VERTICAL = 2
global const int REMAP_DOOR_HORIZONTAL = 3

const asset REMAP_DOOR_MODEL_SINGLE = $"mdl/door/canyonlands_door_single_02.rmdl"
const asset REMAP_DOOR_MODEL_VERTICAL = $"mdl/door/door_canyonlands_large_01_animated.rmdl"
const asset REMAP_DOOR_MODEL_HORIZONTAL = $"mdl/door/door_256x256x8_elevatorstyle02_animated.rmdl"
const asset REMAP_LOOT_BIN_MODEL = $"mdl/props/loot_bin/loot_bin_01_animated.rmdl"
const asset REMAP_JUMP_PAD_MODEL = $"mdl/props/octane_jump_pad/octane_jump_pad.rmdl"
const asset REMAP_JUMP_TOWER_BASE_MODEL = $"mdl/props/zipline_balloon/zipline_balloon_base.rmdl"
const asset REMAP_JUMP_TOWER_BALLOON_MODEL = $"mdl/props/zipline_balloon/zipline_balloon.rmdl"
const asset REMAP_WEAPON_RACK_MODEL = $"mdl/industrial/gun_rack_arm_down.rmdl"
const asset REMAP_WEAPON_RACK_RESPAWN_FX = $"P_impact_shieldbreaker_sparks"
const vector REMAP_WEAPON_RACK_ITEM_OFFSET = < 0, 0, 45 >
const vector REMAP_WEAPON_RACK_ITEM_ANGLES = < -90, 180, 0 >
global const int REMAP_HEAL_MEDKIT = 0
global const int REMAP_HEAL_BATTERY = 1
global const int REMAP_HEAL_SYRINGE = 2
global const int REMAP_HEAL_CELL = 3
global const int REMAP_HEAL_PHOENIX = 4
const asset REMAP_HEAL_MEDKIT_MODEL = $"mdl/weapons_r5/loot/w_loot_wep_iso_health_main_large.rmdl"
const asset REMAP_HEAL_BATTERY_MODEL = $"mdl/weapons_r5/loot/w_loot_wep_iso_shield_battery_large.rmdl"
const asset REMAP_HEAL_SYRINGE_MODEL = $"mdl/weapons_r5/loot/w_loot_wep_iso_health_main_small.rmdl"
const asset REMAP_HEAL_CELL_MODEL = $"mdl/weapons_r5/loot/w_loot_wep_iso_shield_battery_small.rmdl"
const asset REMAP_HEAL_PHOENIX_MODEL = $"mdl/weapons_r5/loot/w_loot_wep_iso_phoenix_kit_v1.rmdl"
const asset REMAP_HEAL_IDLE_FX = $"P_LL_med_drone_jet_ctr_loop"
const string REMAP_HEAL_ACTIVE_SOUND = "Lifeline_Drone_Healing_1P"
const asset REMAP_BUTTON_PANEL_MODEL = $"mdl/props/global_access_panel_button/global_access_panel_button_console_w_stand.rmdl"
const asset REMAP_BUTTON_ARROW_MODEL = $"mdl/weapons/bullets/damage_arrow.rmdl"
const asset REMAP_SPEED_BOOST_ORB_MODEL = $"mdl/fx/plasma_sphere_01.rmdl"
const asset REMAP_SPEED_BOOST_BASE_MODEL = $"mdl/fx/ar_edge_sphere_512.rmdl"
const asset REMAP_SPEED_BOOST_FP_FX = $"P_sprint_FP"
const asset REMAP_BUBBLE_SHIELD_MODEL = $"mdl/fx/bb_shield.rmdl"
const asset REMAP_ANIMATED_CAMERA_BASE_MODEL = $"mdl/IMC_base/camera_imc_base_01.rmdl"
const asset REMAP_ANIMATED_CAMERA_HEAD_MODEL = $"mdl/IMC_base/camera_imc_01.rmdl"

struct
{
	array< entity > props
} file

void function ReMap_ClearProps()
{
	foreach ( entity prop in file.props )
	{
		if ( IsValid( prop ) )
			prop.Destroy()
	}

	file.props.clear()
}

entity function ReMap_CreateProp( asset model, vector origin, vector angles, bool allowMantle = true, float fadeDistance = 50000.0, int realmId = -1, float scale = 1.0 )
{
	entity prop = CreatePropDynamic( model, origin, angles, SOLID_VPHYSICS, fadeDistance )
	prop.kv.fadedist = fadeDistance
	prop.kv.rendermode = 0
	prop.kv.renderamt = 1
	prop.kv.solid = 6
	prop.kv.CollisionGroup = TRACE_COLLISION_GROUP_PLAYER
	prop.SetScriptName( "remap_prop" )
	prop.SetModelScale( scale )

	if ( allowMantle )
		prop.AllowMantle()

	if ( realmId > -1 )
	{
		prop.RemoveFromAllRealms()
		prop.AddToRealm( realmId )
	}

	file.props.append( prop )
	return prop
}

void function ReMap_CreateDoor( vector origin, vector angles, int type = REMAP_DOOR_SINGLE, bool gold = false, bool spawnOpen = false )
{
	switch ( type )
	{
		case REMAP_DOOR_SINGLE:
		{
			entity door = ReMap_CreateDoorEntity( "prop_door", REMAP_DOOR_MODEL_SINGLE, "", origin, angles, gold )
			DispatchSpawn( door )
			if ( spawnOpen )
				ReMap_OpenCodeDoorAtSpawn( door )
			file.props.append( door )
			break
		}

		case REMAP_DOOR_DOUBLE:
		{
			entity door = ReMap_CreateDoorEntity( "prop_door", REMAP_DOOR_MODEL_SINGLE, "", origin, angles, gold )
			door.SetOrigin( origin + door.GetRightVector() * 60.0 )
			DispatchSpawn( door )

			entity oppositeDoor = ReMap_CreateDoorEntity( "prop_door", REMAP_DOOR_MODEL_SINGLE, "", origin,
				< -angles.x, angles.y + 180.0, -angles.z >, gold )
			oppositeDoor.SetOrigin( origin + oppositeDoor.GetRightVector() * 60.0 )
			oppositeDoor.LinkToEnt( door )
			DispatchSpawn( oppositeDoor )

			if ( spawnOpen )
				ReMap_OpenCodeDoorAtSpawn( door )
			file.props.append( door )
			file.props.append( oppositeDoor )
			break
		}

		case REMAP_DOOR_VERTICAL:
		{
			entity door = ReMap_CreateDoorEntity( "prop_dynamic", REMAP_DOOR_MODEL_VERTICAL, "survival_door_plain", origin, angles, false )
			DispatchSpawn( door )
			if ( spawnOpen )
				ReMap_OpenPlainDoorAtSpawn( door )
			file.props.append( door )
			break
		}

		case REMAP_DOOR_HORIZONTAL:
		{
			entity door = ReMap_CreateDoorEntity( "prop_dynamic", REMAP_DOOR_MODEL_HORIZONTAL, "survival_door_plain", origin, angles, false )
			DispatchSpawn( door )
			if ( spawnOpen )
				ReMap_OpenPlainDoorAtSpawn( door )
			file.props.append( door )
			break
		}
	}
}

entity function ReMap_CreateDoorEntity( string entityType, asset model, string scriptName,
	vector origin, vector angles, bool gold )
{
	entity door = CreateEntity( entityType )
	door.SetOrigin( origin )
	door.SetAngles( angles )
	door.SetValueForModelKey( model )

	if ( scriptName != "" )
	{
		door.SetScriptName( scriptName )
		door.kv.solid = 6
	}
	if ( gold )
		door.SetSkin( 1 )

	return door
}

void function ReMap_OpenCodeDoorAtSpawn( entity door )
{
	entity fakeUser = CreateEntity( "prop_dynamic" )
	fakeUser.SetOrigin( door.GetOrigin() - door.GetForwardVector() * 100.0 )
	door.OpenDoor( fakeUser )
	fakeUser.Destroy()
}

void function ReMap_OpenPlainDoorAtSpawn( entity door )
{
	PlayAnimNoWait( door, "open" )
	door.e.isOpen = true
	GradeFlagsSet( door, eGradeFlags.IS_OPEN )
	door.SetUsePrompts( "#SURVIVAL_CLOSE_DOOR", "#SURVIVAL_CLOSE_DOOR" )
}

entity function ReMap_CreateLootBin( vector origin, vector angles, int skin = 0 )
{
	entity lootBin = CreateEntity( "prop_dynamic" )
	if ( Gamemode() == eGamemodes.fs_infected )
		lootBin.SetScriptName( MYSTERY_BOX_SCRIPT_NAME )
	else
		lootBin.SetScriptName( LOOT_BIN_SCRIPTNAME )
	lootBin.SetValueForModelKey( REMAP_LOOT_BIN_MODEL )
	lootBin.SetOrigin( origin )
	lootBin.SetAngles( angles )
	lootBin.kv.solid = SOLID_VPHYSICS
	DispatchSpawn( lootBin )
	lootBin.SetSkin( skin )
	file.props.append( lootBin )
	return lootBin
}

entity function ReMap_CreateButton( vector origin, vector angles, bool visible = true,
	bool up = true, string useText = "" )
{
	entity panel = CreateEntity( "prop_dynamic" )
	panel.SetValueForModelKey( REMAP_BUTTON_PANEL_MODEL )
	panel.SetOrigin( origin )
	panel.SetAngles( angles )
	panel.kv.solid = 0
	DispatchSpawn( panel )
	panel.SetUsable()
	panel.SetUsableByGroup( "pilot" )
	string prompt = useText
	if ( prompt == "" )
		prompt = visible ? "%use% Use" : ( up ? "%use% Next" : "%use% Back" )
	panel.SetUsePrompts( prompt, prompt )
	file.props.append( panel )

	if ( !visible )
	{
		panel.MakeInvisible()
		vector arrowOffset = up ? < 0, 0, -25 > : < 0, 0, 100 >
		vector arrowAngles = up ? < -90, 90, 0 > : < 90, -90, 0 >
		entity arrow = CreateEntity( "prop_dynamic" )
		arrow.SetValueForModelKey( REMAP_BUTTON_ARROW_MODEL )
		arrow.SetOrigin( origin + arrowOffset )
		arrow.SetAngles( angles + arrowAngles )
		arrow.kv.solid = 0
		arrow.kv.fadedist = 300
		DispatchSpawn( arrow )
		arrow.SetModelScale( 10.0 )
		file.props.append( arrow )
	}
	return panel
}

void function ReMap_CreateTeleportButton( vector origin, vector angles, bool up,
	vector destination, vector direction, string message = "", string subMessage = "",
	int messageType = 4, float duration = 5.0, string token = "#FS_STRING_VAR" )
{
	entity panel = ReMap_CreateButton( origin, angles, false, up )
	AddCallback_OnUseEntity( panel, void function( entity usedPanel, entity ent, int input ) :
		( destination, direction, message, subMessage, messageType, duration, token )
	{
		if ( !IsValid( ent ) || !ent.IsPlayer() )
			return
		if ( ent.p.isTimerActive )
		{
			LocalMsg( ent, token, "", messageType, duration,
				"Can't use it while timer is running", "", "", false )
			return
		}
		ent.SetOrigin( destination )
		ent.SetAngles( direction )
		ent.SetVelocity( ZERO_VECTOR )
		if ( message.len() > 0 || subMessage.len() > 0 )
			LocalMsg( ent, token, "", messageType, duration, message, subMessage, "", false )
	} )
}

void function ReMap_CreateSpeedBoost( vector origin, vector color = < 255, 255, 255 >,
	float respawnTime = 5.0, float strength = 0.35, float duration = 3.0,
	float fadeTime = 0.0 )
{
	entity mover = CreateScriptMover( origin, ZERO_VECTOR )
	file.props.append( mover )

	for ( int index = 0; index < 5; index++ )
	{
		entity orb = CreateEntity( "prop_dynamic" )
		orb.SetValueForModelKey( REMAP_SPEED_BOOST_ORB_MODEL )
		orb.SetOrigin( origin + < 0, 0, 50 > )
		orb.SetAngles( < 0, index * 60, 0 > )
		orb.SetModelScale( 0.5 )
		orb.kv.solid = 0
		orb.kv.rendercolor = VectorToString( color )
		orb.kv.fadedist = 20000
		orb.SetParent( mover )
		DispatchSpawn( orb )
		file.props.append( orb )
	}

	entity base = CreateEntity( "prop_dynamic" )
	base.SetValueForModelKey( REMAP_SPEED_BOOST_BASE_MODEL )
	base.SetOrigin( origin )
	base.SetAngles( ZERO_VECTOR )
	base.SetModelScale( 0.1 )
	base.kv.solid = 0
	base.kv.rendercolor = VectorToString( color )
	base.kv.fadedist = 20000
	base.SetParent( mover )
	DispatchSpawn( base )
	file.props.append( base )

	entity trigger = CreateEntity( "trigger_cylinder" )
	trigger.SetRadius( 30 )
	trigger.SetAboveHeight( 30 )
	trigger.SetBelowHeight( 30 )
	trigger.SetOrigin( origin + < 0, 0, 50 > )
	trigger.SetAngles( ZERO_VECTOR )
	trigger.SetParent( mover )
	DispatchSpawn( trigger )
	file.props.append( trigger )
	thread ReMap_SpeedBoostThink( mover, trigger, origin, color, respawnTime,
		strength, duration, fadeTime )
}

entity function ReMap_CreateBubbleShield( vector origin, vector angles,
	float scale = 1.0, vector color = < 128, 255, 128 > )
{
	entity shield = CreateEntity( "prop_dynamic" )
	shield.SetValueForModelKey( REMAP_BUBBLE_SHIELD_MODEL )
	shield.SetOrigin( origin )
	shield.SetAngles( angles )
	shield.SetModelScale( scale )
	shield.kv.solid = SOLID_VPHYSICS
	shield.kv.rendercolor = VectorToString( color )
	shield.kv.contents = int( shield.kv.contents ) | CONTENTS_NOGRAPPLE
	shield.kv.CollisionGroup = TRACE_COLLISION_GROUP_BLOCK_WEAPONS
	DispatchSpawn( shield )
	EmitSoundOnEntity( shield, "Gibraltar_BubbleShield_Sustain" )
	file.props.append( shield )
	return shield
}

entity function ReMap_CreateAnimatedCamera( vector origin, vector angles,
	float angleOffset = 20.0, float maxLeft = 20.0, float maxRight = 40.0,
	float rotationTime = 4.0, float transitionTime = 2.0 )
{
	entity mover = CreateScriptMover( origin, ZERO_VECTOR )
	entity cameraBase = CreateEntity( "prop_dynamic" )
	cameraBase.SetValueForModelKey( REMAP_ANIMATED_CAMERA_BASE_MODEL )
	cameraBase.SetOrigin( origin )
	cameraBase.SetAngles( ZERO_VECTOR )
	cameraBase.kv.solid = SOLID_VPHYSICS
	DispatchSpawn( cameraBase )
	cameraBase.SetParent( mover )

	entity cameraHead = CreateScriptMoverModel( REMAP_ANIMATED_CAMERA_HEAD_MODEL,
		origin + < 16, 0, 8 >, < angleOffset, 0, 0 >, SOLID_VPHYSICS )
	cameraHead.SetParent( mover )
	mover.SetAngles( angles )
	file.props.append( mover )
	file.props.append( cameraBase )
	file.props.append( cameraHead )
	thread ReMap_AnimateCamera( cameraHead, maxLeft, maxRight, rotationTime, transitionTime )
	return mover
}

entity function ReMap_CreateSound( vector origin, string soundName, float radius = 0.0,
	bool isWaveAmbient = false, bool enabled = true, array<vector> polylinePoints = [] )
{
	entity sound = CreateEntity( "ambient_generic" )
	sound.SetOrigin( origin )
	sound.SetValueForKey( "radius", string( radius ) )
	sound.SetValueForKey( "isWaveAmbient", isWaveAmbient ? "1" : "0" )
	for ( int index = 0; index < polylinePoints.len(); index++ )
	{
		vector start = index == 0 ? ZERO_VECTOR : polylinePoints[index - 1] - origin
		vector end = polylinePoints[index] - origin
		sound.SetValueForKey( "polyline_segment_" + index,
			"(" + VectorToString( start ) + ") (" + VectorToString( end ) + ")" )
	}
	sound.SetSoundName( soundName )
	sound.SetEnabled( enabled )
	DispatchSpawn( sound )
	file.props.append( sound )
	return sound
}

void function ReMap_AnimateCamera( entity cameraHead, float maxLeft, float maxRight,
	float rotationTime, float transitionTime )
{
	vector baseAngles = cameraHead.GetAngles()
	float blendTime = rotationTime * 0.5
	while ( IsValid( cameraHead ) )
	{
		cameraHead.NonPhysicsRotateTo( baseAngles + < 0, maxLeft, 0 >,
			rotationTime, blendTime, blendTime )
		wait rotationTime + transitionTime
		if ( !IsValid( cameraHead ) )
			return
		cameraHead.NonPhysicsRotateTo( baseAngles - < 0, maxRight, 0 >,
			rotationTime, blendTime, blendTime )
		wait rotationTime + transitionTime
	}
}

void function ReMap_SpeedBoostThink( entity mover, entity trigger, vector origin, vector color,
	float respawnTime, float strength, float duration, float fadeTime )
{
	while ( IsValid( trigger ) )
	{
		foreach ( entity touchingEnt in trigger.GetTouchingEntities() )
		{
			if ( !IsValid( touchingEnt ) || !touchingEnt.IsPlayer() )
				continue
			StatusEffect_AddTimed( touchingEnt, eStatusEffect.speed_boost,
				strength, duration, fadeTime )
			thread ReMap_PlaySpeedBoostFx( touchingEnt, duration )
			if ( IsValid( mover ) )
				mover.Destroy()
			wait respawnTime
			ReMap_CreateSpeedBoost( origin, color, respawnTime, strength, duration, fadeTime )
			return
		}
		wait 0.1
	}
}

void function ReMap_PlaySpeedBoostFx( entity player, float duration )
{
	if ( !IsValid( player ) )
		return
	player.EndSignal( "OnDeath" )
	player.EndSignal( "OnDestroy" )
	entity fx = PlayLoopFXOnEntity( REMAP_SPEED_BOOST_FP_FX, player )
	OnThreadEnd( function() : ( fx )
	{
		if ( IsValid( fx ) )
			fx.Destroy()
	} )
	wait duration
}

entity function ReMap_CreateJumpPad( vector origin, vector angles, bool allowMantle = true, float fadeDistance = 50000.0, int realmId = -1, float scale = 1.0, float launchVelocity = 1000.0, float forwardScale = 1.7, float radius = 45.0, bool doubleJump = true )
{
	entity jumpPad = ReMap_CreateProp( REMAP_JUMP_PAD_MODEL, origin, angles, allowMantle,
		fadeDistance, realmId, scale )
	jumpPad.SetScriptName( "remap_jump_pad" )
	jumpPad.kv.contents = CONTENTS_HITBOX | CONTENTS_BULLETCLIP
	PlayAnimNoWait( jumpPad, "prop_octane_jump_pad_deploy_idle" )

	entity trigger = CreateEntity( "trigger_cylinder_heavy" )
	trigger.SetOwner( jumpPad )
	trigger.SetRadius( radius * scale )
	trigger.SetAboveHeight( 32.0 * scale )
	trigger.SetBelowHeight( 16.0 * scale )
	trigger.SetOrigin( origin )
	trigger.SetAngles( angles )
	trigger.SetTriggerType( TT_JUMP_PAD )
	trigger.SetLaunchScaleValues( launchVelocity, forwardScale )
	trigger.SetViewPunchValues( 15.0, 4.0, 0.0 )
	trigger.UsePointCollision()
	trigger.kv.triggerFilterNonCharacter = "0"
	trigger.s.remapDoubleJump <- doubleJump
	DispatchSpawn( trigger )
	trigger.SetEnterCallback( ReMap_OnJumpPadEnter )
	trigger.SetParent( jumpPad )
	trigger.RemoveFromAllRealms()
	trigger.AddToOtherEntitysRealms( jumpPad )
	file.props.append( trigger )
	return jumpPad
}

void function ReMap_OnJumpPadEnter( entity trigger, entity ent )
{
	if ( !IsValid( ent ) || !ent.IsPlayer() )
		return

	entity jumpPad = trigger.GetOwner()
	if ( IsValid( jumpPad ) )
		PlayAnimNoWait( jumpPad, "prop_octane_jump_pad_deploy_trans" )

	ent.kv.gravity = 0.75
	JumpPadPushEnt( trigger, ent, trigger.GetOrigin(), trigger.GetAngles() )
	thread ReMap_RestoreJumpPadGravity( ent )
	if ( trigger.s.remapDoubleJump )
		thread ReMap_GiveJumpPadDoubleJump( ent )
}

void function ReMap_RestoreJumpPadGravity( entity player )
{
	player.EndSignal( "OnDeath" )
	player.EndSignal( "OnDestroy" )
	OnThreadEnd( function() : ( player )
	{
		if ( IsValid( player ) )
			player.kv.gravity = 1.0
	} )

	WaitFrame()
	while ( IsValid( player ) && !player.IsOnGround() && !player.IsZiplining() )
		WaitFrame()
}

void function ReMap_GiveJumpPadDoubleJump( entity player )
{
	if ( !IsValid( player ) || !player.IsPlayer() )
		return

	player.EndSignal( "OnDeath" )
	player.EndSignal( "OnDestroy" )
	wait 0.1
	if ( !IsValid( player ) || player.IsOnGround() )
		return

	asset storedSettings = player.GetPlayerSettings()
	array< string > storedMods = clone player.GetPlayerSettingsMods()
	array< string > newMods = clone storedMods
	bool alreadyEnabled = false
	foreach ( string mod in newMods )
	{
		if ( mod == "enable_doublejump" )
			alreadyEnabled = true
	}
	if ( !alreadyEnabled )
		newMods.append( "enable_doublejump" )

	int health = player.GetHealth()
	int shields = player.GetShieldHealth()
	player.SetPlayerSettingsWithMods( storedSettings, newMods )
	player.SetHealth( health )
	player.SetShieldHealth( shields )
	AddButtonPressedPlayerInputCallback( player, IN_JUMP, ReMap_ConsumeJumpPadDoubleJump )

	OnThreadEnd( function() : ( player, storedSettings, storedMods )
	{
		if ( !IsValid( player ) )
			return
		RemoveButtonPressedPlayerInputCallback( player, IN_JUMP, ReMap_ConsumeJumpPadDoubleJump )
		if ( IsAlive( player ) )
		{
			int currentHealth = player.GetHealth()
			int currentShields = player.GetShieldHealth()
			player.SetPlayerSettingsWithMods( storedSettings, storedMods )
			player.SetHealth( currentHealth )
			player.SetShieldHealth( currentShields )
		}
	} )

	while ( IsValid( player ) && !player.IsOnGround() && !player.IsZiplining() )
		WaitFrame()
}

void function ReMap_ConsumeJumpPadDoubleJump( entity player )
{
	if ( !IsValid( player ) || !IsAlive( player ) )
		return
	player.ConsumeDoubleJump()
	RemoveButtonPressedPlayerInputCallback( player, IN_JUMP, ReMap_ConsumeJumpPadDoubleJump )
}

entity function ReMap_CreateSpawnPoint( vector origin, vector angles, int teamNumber = 0 )
{
	entity spawnPoint = CreateEntity( "info_spawnpoint_human" )
	spawnPoint.SetOrigin( origin )
	spawnPoint.SetAngles( angles )
	spawnPoint.SetValueForModelKey( $"mdl/dev/mp_spawn.rmdl" )
	spawnPoint.kv.teamnumber = teamNumber
	spawnPoint.kv.control_teamnumber = -1
	spawnPoint.kv.phase_1 = 0
	spawnPoint.kv.phase_2 = 0
	spawnPoint.kv.phase_3 = 0
	spawnPoint.kv.phase_4 = 0
	spawnPoint.kv.phase_5 = 0
	spawnPoint.kv.phase_6 = 0
	spawnPoint.kv.phase_7 = 0
	spawnPoint.kv.phase_8 = 0
	spawnPoint.kv.phase_9 = 0
	spawnPoint.kv.gamemode_tdm = 1
	spawnPoint.kv.gamemode_ffa = 1
	spawnPoint.kv.gamemode_fd = 1
	spawnPoint.kv.gamemode_ctf = 1
	spawnPoint.kv.gamemode_cp = 1
	spawnPoint.kv.gamemode_at = 1
	spawnPoint.kv.gamemode_fw = 0
	spawnPoint.kv.gamemode_freelance = 0
	DispatchSpawn( spawnPoint )
	file.props.append( spawnPoint )
	return spawnPoint
}

entity function ReMap_CreateTrigger( vector origin, vector angles, float radius,
	float halfHeight, bool debugDraw = false, int realmId = -1 )
{
	entity trigger = CreateEntity( "trigger_cylinder" )
	trigger.SetRadius( radius )
	trigger.SetAboveHeight( halfHeight )
	trigger.SetBelowHeight( halfHeight )
	trigger.SetOrigin( origin )
	trigger.SetAngles( angles )
	if ( realmId > -1 )
	{
		trigger.RemoveFromAllRealms()
		trigger.AddToRealm( realmId )
	}
	if ( debugDraw )
	{
		DebugDrawCylinder( origin, < -90, 0, 0 >, radius, halfHeight,
			0, 165, 255, true, 9999.9 )
		DebugDrawCylinder( origin, < -90, 0, 0 >, radius, -halfHeight,
			255, 90, 0, true, 9999.9 )
	}
	file.props.append( trigger )
	return trigger
}

void function ReMap_CreateJumpTower( vector origin, vector angles, float height = 2000.0 )
{
	vector towerAngles = < 0, angles.y, 0 >
	entity towerBase = CreateEntity( "prop_dynamic" )
	towerBase.SetOrigin( origin )
	towerBase.SetAngles( towerAngles )
	towerBase.SetValueForModelKey( REMAP_JUMP_TOWER_BASE_MODEL )
	towerBase.kv.solid = 6
	towerBase.AllowMantle()

	entity balloon = CreateEntity( "prop_dynamic" )
	balloon.SetOrigin( origin + < 0, 0, height > )
	balloon.SetAngles( towerAngles )
	balloon.SetValueForModelKey( REMAP_JUMP_TOWER_BALLOON_MODEL )
	balloon.kv.solid = 3

	foreach ( entity part in [ towerBase, balloon ] )
	{
		part.kv.fadedist = -1
		part.kv.renderamt = 255
		part.kv.rendercolor = "255 255 255"
		part.kv.CollisionGroup = TRACE_COLLISION_GROUP_PLAYER
		part.SetScriptName( "jump_tower" )
		DispatchSpawn( part )
		file.props.append( part )
	}

	vector topCable = PositionOffsetFromEnt( balloon, -1.75, -2.75, 0 )
	vector bottomCable = PositionOffsetFromEnt( towerBase, -1.75, -2.75, 64 )
	ReMap_CreateZipline( topCable, towerAngles, bottomCable, towerAngles,
		REMAP_ZIPLINE_END_NONE, REMAP_ZIPLINE_END_NONE, true, 2.0, 1.0,
		180.0, 180.0, true, 1.0, angles.y, -1.0, 1.0,
		false, true, 200.0, 200.0, false, false, false )

	entity skydiveTrigger = ReMap_CreateTrigger( origin + < 0, 0, height - 20.0 >,
		towerAngles, 200.0, 200.0, false, -1 )
	skydiveTrigger.SetEnterCallback( ForcedSkydiveTriggerThink_EnterCallback )
	DispatchSpawn( skydiveTrigger )
}

entity function ReMap_CreateWeaponRack( vector origin, vector angles, string weaponName,
	float respawnTime = 0.5 )
{
	entity rack = CreateEntity( "prop_dynamic" )
	rack.SetScriptName( "weaponrack_spawned" )
	rack.SetValueForModelKey( REMAP_WEAPON_RACK_MODEL )
	rack.SetOrigin( origin )
	rack.SetAngles( angles )
	rack.kv.solid = SOLID_VPHYSICS
	rack.AllowMantle()
	DispatchSpawn( rack )
	file.props.append( rack )

	entity weapon = ReMap_SpawnWeaponRackItem( rack, weaponName )
	if ( IsValid( weapon ) )
		thread ReMap_WeaponRackRespawnThread( rack, weapon, weaponName, respawnTime )
	return rack
}

entity function ReMap_SpawnWeaponRackItem( entity rack, string weaponName )
{
	if ( !IsValid( rack ) || weaponName.len() == 0 )
		return null

	entity weapon = SpawnGenericLoot( weaponName,
		rack.GetOrigin() + REMAP_WEAPON_RACK_ITEM_OFFSET,
		rack.GetAngles() + REMAP_WEAPON_RACK_ITEM_ANGLES,
		1, TRACE_COLLISION_GROUP_NONE, false, 0, true )
	if ( !IsValid( weapon ) )
		return null
	weapon.SetParent( rack )
	return weapon
}

void function ReMap_WeaponRackRespawnThread( entity rack, entity weapon, string weaponName,
	float respawnTime )
{
	rack.EndSignal( "OnDestroy" )
	weapon.WaitSignal( "OnItemPickup" )
	wait respawnTime

	if ( !IsValid( rack ) )
		return
	entity replacement = ReMap_SpawnWeaponRackItem( rack, weaponName )
	if ( !IsValid( replacement ) )
		return
	StartParticleEffectInWorld( GetParticleSystemIndex( REMAP_WEAPON_RACK_RESPAWN_FX ),
		replacement.GetOrigin(), replacement.GetAngles() )
	thread ReMap_WeaponRackRespawnThread( rack, replacement, weaponName, respawnTime )
}

void function ReMap_CreateRespawnHeal( vector origin, int healType = REMAP_HEAL_MEDKIT, float respawnTime = 6.0, float healDuration = 5.0, int healAmount = 25, bool progressive = true )
{
	entity pickup = CreateEntity( "prop_dynamic" )
	pickup.SetOrigin( origin )
	pickup.SetAngles( ZERO_VECTOR )
	pickup.SetValueForModelKey( ReMap_RespawnHealModel( healType ) )
	pickup.kv.fadedist = 50000
	pickup.kv.renderamt = 255
	pickup.kv.rendercolor = "255 255 255 200"
	pickup.kv.solid = 0
	DispatchSpawn( pickup )
	pickup.NotSolid()
	SetSurvivalPropHighlight( pickup, ReMap_RespawnHealHighlight( healType ), false )
	EmitSoundOnEntity( pickup, ReMap_RespawnHealPickupSound( healType ) )
	thread ReMap_RotateRespawnHeal( pickup )

	entity trigger = CreateEntity( "trigger_cylinder" )
	trigger.SetRadius( 50 )
	trigger.SetAboveHeight( 60 )
	trigger.SetBelowHeight( 0 )
	trigger.SetOrigin( origin )
	trigger.s.remapPickup <- pickup
	trigger.s.remapHealType <- healType
	trigger.s.remapRespawnTime <- respawnTime
	trigger.s.remapHealDuration <- healDuration
	trigger.s.remapHealAmount <- healAmount
	trigger.s.remapProgressive <- progressive
	trigger.s.remapActive <- true
	trigger.s.remapFx <- ReMap_StartRespawnHealEffects( pickup )
	DispatchSpawn( trigger )
	trigger.SetEnterCallback( ReMap_OnRespawnHealEnter )

	file.props.append( pickup )
	file.props.append( trigger )
}

void function ReMap_OnRespawnHealEnter( entity trigger, entity player )
{
	if ( !IsValid( player ) || !player.IsPlayer() || !trigger.s.remapActive )
		return
	int healType = expect int( trigger.s.remapHealType )
	bool needsHealth = player.GetHealth() < player.GetMaxHealth()
	bool needsShield = player.GetShieldHealth() < player.GetShieldHealthMax()
	if ( ( healType == REMAP_HEAL_MEDKIT || healType == REMAP_HEAL_SYRINGE ) && !needsHealth )
		return
	if ( ( healType == REMAP_HEAL_BATTERY || healType == REMAP_HEAL_CELL ) && !needsShield )
		return
	if ( healType == REMAP_HEAL_PHOENIX && !needsHealth && !needsShield )
		return

	trigger.s.remapActive = false
	entity pickup = expect entity( trigger.s.remapPickup )
	pickup.kv.rendercolor = "255 255 255 40"
	foreach ( entity fx in expect array<entity>( trigger.s.remapFx ) )
		if ( IsValid( fx ) ) fx.Destroy()
	trigger.s.remapFx.clear()
	thread ReMap_ConsumeRespawnHeal( trigger, player )
}

void function ReMap_ConsumeRespawnHeal( entity trigger, entity player )
{
	trigger.EndSignal( "OnDestroy" )
	int healType = expect int( trigger.s.remapHealType )
	float duration = expect float( trigger.s.remapHealDuration )
	int amount = expect int( trigger.s.remapHealAmount )
	bool progressive = expect bool( trigger.s.remapProgressive )
	int startHealth = player.GetHealth()
	int startShield = player.GetShieldHealth()
	int targetHealth = startHealth
	int targetShield = startShield
	if ( healType == REMAP_HEAL_MEDKIT || healType == REMAP_HEAL_PHOENIX ) targetHealth = player.GetMaxHealth()
	if ( healType == REMAP_HEAL_SYRINGE ) targetHealth = min( player.GetMaxHealth(), startHealth + amount )
	if ( healType == REMAP_HEAL_BATTERY || healType == REMAP_HEAL_PHOENIX ) targetShield = player.GetShieldHealthMax()
	if ( healType == REMAP_HEAL_CELL ) targetShield = min( player.GetShieldHealthMax(), startShield + amount )

	if ( IsValid( player ) )
	{
		StatusEffect_StopAllOfType( player, eStatusEffect.drone_healing )
		StatusEffect_AddEndless( player, eStatusEffect.drone_healing, 1 )
		EmitSoundOnEntityOnlyToPlayer( player, player, REMAP_HEAL_ACTIVE_SOUND )
	}
	if ( progressive )
	{
		int steps = maxint( 1, int( duration / 0.05 ) )
		for ( int step = 1; step <= steps && IsValid( player ); step++ )
		{
			float fraction = float( step ) / float( steps )
			player.SetHealth( int( startHealth + float( targetHealth - startHealth ) * fraction ) )
			player.SetShieldHealth( int( startShield + float( targetShield - startShield ) * fraction ) )
			wait duration / float( steps )
		}
	}
	else
	{
		wait duration
		if ( IsValid( player ) )
		{
			player.SetHealth( targetHealth )
			player.SetShieldHealth( targetShield )
		}
	}
	if ( IsValid( player ) )
	{
		StopSoundOnEntity( player, REMAP_HEAL_ACTIVE_SOUND )
		StatusEffect_StopAllOfType( player, eStatusEffect.drone_healing )
	}
	wait expect float( trigger.s.remapRespawnTime )
	if ( !IsValid( trigger ) ) return
	entity pickup = expect entity( trigger.s.remapPickup )
	if ( !IsValid( pickup ) ) return
	pickup.kv.rendercolor = "255 255 255 200"
	trigger.s.remapFx = ReMap_StartRespawnHealEffects( pickup )
	EmitSoundOnEntity( pickup, ReMap_RespawnHealPickupSound( healType ) )
	trigger.s.remapActive = true
}

array<entity> function ReMap_StartRespawnHealEffects( entity pickup )
{
	array<entity> effects
	for ( int index = 0; index < 4; index++ )
	{
		entity fx = StartParticleEffectInWorld_ReturnEntity( GetParticleSystemIndex( REMAP_HEAL_IDLE_FX ),
			pickup.GetOrigin(), < 0, index * 90, 0 > )
		fx.SetParent( pickup )
		effects.append( fx )
	}
	return effects
}

void function ReMap_RotateRespawnHeal( entity pickup )
{
	while ( IsValid( pickup ) )
	{
		vector angles = pickup.GetAngles()
		pickup.SetAngles( < angles.x, angles.y + 7.0 * FrameTime(), angles.z > )
		WaitFrame()
	}
}

asset function ReMap_RespawnHealModel( int healType )
{
	switch ( healType )
	{
		case REMAP_HEAL_BATTERY: return REMAP_HEAL_BATTERY_MODEL
		case REMAP_HEAL_SYRINGE: return REMAP_HEAL_SYRINGE_MODEL
		case REMAP_HEAL_CELL: return REMAP_HEAL_CELL_MODEL
		case REMAP_HEAL_PHOENIX: return REMAP_HEAL_PHOENIX_MODEL
	}
	return REMAP_HEAL_MEDKIT_MODEL
}

string function ReMap_RespawnHealHighlight( int healType )
{
	if ( healType == REMAP_HEAL_PHOENIX ) return "survival_item_epic"
	if ( healType == REMAP_HEAL_MEDKIT || healType == REMAP_HEAL_BATTERY ) return "survival_item_rare"
	return "survival_item_common"
}

string function ReMap_RespawnHealPickupSound( int healType )
{
	if ( healType == REMAP_HEAL_MEDKIT ) return "survival_loot_pickup_Medkit_3P"
	if ( healType == REMAP_HEAL_SYRINGE ) return "survival_loot_pickup_3p_small_health"
	return "survival_loot_pickup_Battery_Shield_3p"
}
