// Generated by ReMap for R5Flowstate.
// Source code: https://github.com/ReMap
// Do not edit this file directly; rebuild it from the ReMap sources.

/*
 * ReMap game scripts
 *
 * Source lineage: rewritten from the active R5Reloaded ReMap implementation
 * and the legacy ReMap zipline scripts.
 * Original ReMap: Zee (@AyeZeeBB on X, zee_x64 on Discord)
 * and Julefox (@Julefox_ on X, julefox on Discord).
 * This standalone ReMap rewrite was created and is maintained by Julefox.
 *
 * Made with love for the Apex modding community. <3
 * Built on the Apex modding foundation created by Amos (@AmosModz on X, amosmodz on Discord):
 * https://github.com/Mauler125/r5sdk
 */

global function ReMap_PrecacheZiplines
global function ReMap_ClearZiplines
global function ReMap_CreateZipline
global function ReMap_CreateCurvedZipline
global function ReMap_CreateZiprail

global const int REMAP_ZIPLINE_END_NONE = 0
global const int REMAP_ZIPLINE_END_ARM = 1
global const int REMAP_ZIPLINE_END_SUPPORT = 2

const asset REMAP_ZIPLINE_MODEL_ARM = $"mdl/industrial/zipline_arm.rmdl"
const asset REMAP_ZIPLINE_MODEL_SUPPORT = $"mdl/industrial/security_fence_post.rmdl"
global const int REMAP_ZIPRAIL_POINT_NONE = 0
global const int REMAP_ZIPRAIL_POINT_ARM = 1
global const int REMAP_ZIPRAIL_POINT_SUPPORT = 2
global const int REMAP_ZIPRAIL_POINT_BUILDING_CLAW_02 = 3
global const int REMAP_ZIPRAIL_POINT_WALL = 4

const asset REMAP_ZIPRAIL_MODEL_BUILDING_CLAW = $"mdl/props/zip_rail/zip_rail_building_claw_01.rmdl"
const asset REMAP_ZIPRAIL_MODEL_BUILDING_CLAW_02 = $"mdl/props/zip_rail/zip_rail_building_claw_02.rmdl"
const asset REMAP_ZIPRAIL_MODEL_WALL = $"mdl/props/zip_rail/zip_rail_wall_01.rmdl"
const asset REMAP_ZIPRAIL_MODEL_CORD_END = $"mdl/props/zip_rail/zip_rail_cord_end_01.rmdl"
const asset REMAP_ZIPRAIL_MODEL_GROUND_BASE = $"mdl/props/zip_rail/zip_rail_ground_base_01.rmdl"
const asset REMAP_ZIPRAIL_MODEL_GROUND_CLAW = $"mdl/props/zip_rail/zip_rail_ground_claw_01.rmdl"
const asset REMAP_ZIPRAIL_MODEL_GROUND_POST = $"mdl/props/zip_rail/zip_rail_ground_post_01.rmdl"
const asset REMAP_ZIPRAIL_MODEL_GROUND_POST_TOP = $"mdl/props/zip_rail/zip_rail_ground_post_top_01.rmdl"

struct
{
	array< entity > entities
} file

void function ReMap_PrecacheZiplines()
{
	PrecacheModel( REMAP_ZIPLINE_MODEL_ARM )
	PrecacheModel( REMAP_ZIPLINE_MODEL_SUPPORT )
}

void function ReMap_ClearZiplines()
{
	foreach ( entity ent in file.entities )
	{
		if ( IsValid( ent ) )
			ent.Destroy()
	}

	file.entities.clear()
}

void function ReMap_CreateZipline( vector startOrigin, vector startAngles, vector endOrigin, vector endAngles, int startProfile = REMAP_ZIPLINE_END_ARM, int endProfile = REMAP_ZIPLINE_END_ARM, bool vertical = false, float width = 2.0, float speedScale = 1.0, float startArmHeight = 180.0, float endArmHeight = 180.0, bool pushOffInDirectionX = false, float lengthScale = 1.0, float pushOffAngle = 0.0, float fadeDistance = -1.0, float ziplineScale = 1.0, bool preserveVelocity = false, bool dropToBottom = true, float startAutoDetachDistance = 100.0, float endAutoDetachDistance = 100.0, bool restPoint = false, bool detachEndOnSpawn = false, bool detachEndOnUse = false )
{
	if ( startOrigin == endOrigin )
		return

	vector startCableOrigin = ReMap_CreateZiplineEndModel( startProfile, startOrigin, startAngles, startArmHeight )
	vector endCableOrigin = ReMap_CreateZiplineEndModel( vertical ? REMAP_ZIPLINE_END_NONE : endProfile, endOrigin, endAngles, endArmHeight )
	vector startCableAngles = startAngles
	vector endCableAngles = endAngles

	if ( vertical )
	{
		endCableOrigin = <startCableOrigin.x, startCableOrigin.y, endCableOrigin.z>
		startCableAngles = <0.0, pushOffAngle, 0.0>
		endCableAngles = startCableAngles
	}
	else
	{
		startCableAngles = VectorToAngles( Normalize( endCableOrigin - startCableOrigin ) )
		endCableAngles = VectorToAngles( Normalize( startCableOrigin - endCableOrigin ) )
	}

	entity startPoint = CreateEntity( "zipline" )
	startPoint.kv.DetachEndOnSpawn = detachEndOnSpawn ? 1 : 0
	startPoint.kv.DetachEndOnUse = detachEndOnUse ? 1 : 0
	startPoint.kv.Material = "cable/zipline.vmt"
	startPoint.kv.scale = ziplineScale
	startPoint.kv.Width = width
	startPoint.kv.ZiplineAutoDetachDistance = startAutoDetachDistance
	startPoint.kv.ZiplineDropToBottom = dropToBottom ? 1 : 0
	startPoint.kv.ZiplineFadeDistance = fadeDistance
	startPoint.kv.ZiplineLengthScale = lengthScale
	startPoint.kv.ZiplinePreserveVelocity = preserveVelocity ? 1 : 0
	startPoint.kv.ZiplinePushOffInDirectionX = pushOffInDirectionX ? 1 : 0
	startPoint.kv.ZiplineSpeedScale = speedScale
	startPoint.kv.ZiplineVersion = 3
	startPoint.kv.ZiplineVertical = vertical
	if ( restPoint )
	{
		startPoint.kv._zipline_rest_point_0 = startCableOrigin.x + " " + startCableOrigin.y + " " + startCableOrigin.z
		startPoint.kv._zipline_rest_point_1 = endCableOrigin.x + " " + endCableOrigin.y + " " + endCableOrigin.z
	}
	startPoint.SetAngles( startCableAngles )
	startPoint.SetOrigin( startCableOrigin )

	entity endPoint = CreateEntity( "zipline_end" )
	endPoint.kv.ZiplineAutoDetachDistance = endAutoDetachDistance
	endPoint.kv.ZiplinePushOffInDirectionX = pushOffInDirectionX ? 1 : 0
	endPoint.SetAngles( endCableAngles )
	endPoint.SetOrigin( endCableOrigin )

	startPoint.LinkToEnt( endPoint )
	DispatchSpawn( startPoint )
	DispatchSpawn( endPoint )
	file.entities.append( startPoint )
	file.entities.append( endPoint )
}

void function ReMap_CreateCurvedZipline( array<vector> controlPoints, int segmentsPerSpan = 8,
	array<int> pointProfiles = [], array<vector> pointAngles = [],
	array<float> pointArmHeights = [], float width = 2.0, float speedScale = 1.0 )
{
	if ( controlPoints.len() < 2 )
		return

	array<vector> adjustedPoints = clone controlPoints
	for ( int index = 0; index < adjustedPoints.len(); index++ )
	{
		int profile = index < pointProfiles.len() ? pointProfiles[index] : REMAP_ZIPLINE_END_NONE
		vector angles = index < pointAngles.len() ? pointAngles[index] : <0, 0, 0>
		float armHeight = index < pointArmHeights.len() ? pointArmHeights[index] : 180.0
		adjustedPoints[index] = ReMap_CreateCurvedZiplinePointModel(
			profile, adjustedPoints[index], angles, armHeight )
	}
	array<vector> curvePoints = ReMap_BuildBezierPath( adjustedPoints, segmentsPerSpan )
	if ( curvePoints.len() < 2 )
		return

	array<entity> ropes
	for ( int index = 0; index < curvePoints.len(); index++ )
	{
		entity rope = ReMap_SetCurvedRopeProperties(
			CreateEntity( index == 0 ? "move_rope" : "keyframe_rope" ), width, speedScale )
		rope.SetOrigin( curvePoints[index] )
		ropes.append( rope )
	}

	for ( int index = 0; index < ropes.len() - 1; index++ )
		ropes[index].LinkToEnt( ropes[index + 1] )
	foreach ( entity rope in ropes )
	{
		DispatchSpawn( rope )
		file.entities.append( rope )
	}
}

entity function ReMap_SetCurvedRopeProperties( entity rope, float width, float speedScale )
{
	rope.kv.MoveSpeed = 64.0 * speedScale
	rope.kv.Slack = 25
	rope.kv.Subdiv = "2"
	rope.kv.Width = width
	rope.kv.Type = "0"
	rope.kv.TextureScale = "1"
	rope.kv.PositionInterpolator = 2
	rope.kv.RopeMaterial = "cable/zipline.vmt"
	rope.kv.Zipline = "1"
	rope.kv.ZiplineAutoDetachDistance = "150"
	rope.kv.ZiplineSagEnable = "0"
	rope.kv.ZiplineSagHeight = "50"
	rope.kv.fadedist = 50000
	return rope
}

vector function ReMap_CreateCurvedZiplinePointModel( int profile, vector origin, vector angles,
	float armHeight )
{
	vector armOrigin = origin
	if ( profile == REMAP_ZIPLINE_END_SUPPORT )
	{
		entity support = CreateEntity( "prop_dynamic" )
		support.SetOrigin( origin )
		support.SetAngles( angles )
		support.SetValueForModelKey( REMAP_ZIPLINE_MODEL_SUPPORT )
		support.kv.solid = 0
		support.kv.contents = 0
		DispatchSpawn( support )
		file.entities.append( support )
		armOrigin = origin + RotateVector( <4, -2.5, armHeight>, angles )
	}
	if ( profile != REMAP_ZIPLINE_END_ARM && profile != REMAP_ZIPLINE_END_SUPPORT )
		return origin

	entity arm = CreateEntity( "prop_dynamic" )
	arm.SetOrigin( armOrigin )
	arm.SetAngles( <angles.x, angles.y + 90.0, angles.z> )
	arm.SetValueForModelKey( REMAP_ZIPLINE_MODEL_ARM )
	arm.kv.solid = 0
	arm.kv.contents = 0
	DispatchSpawn( arm )
	file.entities.append( arm )
	return armOrigin + RotateVector( <-58, -2, -14>, angles )
}

array<vector> function ReMap_BuildBezierPath( array<vector> points, int segmentsPerSpan )
{
	if ( segmentsPerSpan < 2 )
		segmentsPerSpan = 2
	else if ( segmentsPerSpan > 32 )
		segmentsPerSpan = 32
	array<vector> tangents
	tangents.append( (points[1] - points[0]) * 0.5 )
	for ( int index = 1; index < points.len() - 1; index++ )
	{
		vector direction = points[index + 1] - points[index - 1]
		float tangentLength = min( Distance( points[index - 1], points[index] ),
			Distance( points[index], points[index + 1] ) ) * 0.5
		tangents.append( Length( direction ) < 0.001 ? <0, 0, 0> : Normalize( direction ) * tangentLength )
	}
	tangents.append( (points[points.len() - 1] - points[points.len() - 2]) * 0.5 )

	array<vector> curvePoints = [points[0]]
	for ( int span = 0; span < points.len() - 1; span++ )
	{
		vector p0 = points[span]
		vector p1 = p0 + tangents[span]
		vector p3 = points[span + 1]
		vector p2 = p3 - tangents[span + 1]
		for ( int segment = 1; segment <= segmentsPerSpan; segment++ )
		{
			float t = float( segment ) / float( segmentsPerSpan )
			curvePoints.append( ReMap_BezierPoint( p0, p1, p2, p3, t ) )
		}
	}
	return curvePoints
}

vector function ReMap_BezierPoint( vector p0, vector p1, vector p2, vector p3, float t )
{
	vector a = p0 + (p1 - p0) * t
	vector b = p1 + (p2 - p1) * t
	vector c = p2 + (p3 - p2) * t
	vector d = a + (b - a) * t
	vector e = b + (c - b) * t
	return d + (e - d) * t
}

vector function ReMap_CreateZiplineEndModel( int profile, vector origin, vector angles, float armHeight = 180.0 )
{
	vector armAngles = <angles.x, angles.y + 90.0, angles.z>
	if ( profile == REMAP_ZIPLINE_END_ARM )
	{
		ReMap_CreateProp( REMAP_ZIPLINE_MODEL_ARM, origin, armAngles )
		return origin + RotateVector( <-58, -2, -14>, angles )
	}
	else if ( profile == REMAP_ZIPLINE_END_SUPPORT )
	{
		ReMap_CreateProp( REMAP_ZIPLINE_MODEL_SUPPORT, origin, angles )
		vector armOrigin = origin + RotateVector( <4, -2.5, armHeight>, angles )
		ReMap_CreateProp( REMAP_ZIPLINE_MODEL_ARM, armOrigin, armAngles )
		return armOrigin + RotateVector( <-58, -2, -14>, angles )
	}

	return origin
}

void function ReMap_CreateZiprail( array<vector> controlPoints,
	array<int> pointProfiles = [], array<vector> pointAngles = [],
	array<float> pointSupportHeights = [], float width = 1.75,
	float speedScale = 1.75, float startAutoDetachDistance = 0.0,
	float endAutoDetachDistance = 0.0 )
{
	if ( controlPoints.len() < 2 )
		return

	for ( int index = 1; index < controlPoints.len(); index++ )
	{
		if ( Distance( controlPoints[index - 1], controlPoints[index] ) < 0.01 )
			return
	}

	for ( int index = 0; index < controlPoints.len(); index++ )
	{
		int profile = index < pointProfiles.len() ? pointProfiles[index] : REMAP_ZIPRAIL_POINT_NONE
		vector angles = index < pointAngles.len() ? pointAngles[index] : <0, 0, 0>
		float supportHeight = index < pointSupportHeights.len() ? pointSupportHeights[index] : 320.0
		ReMap_CreateZiprailPointModels( profile, controlPoints[index], angles, supportHeight )
	}

	array<entity> nodes
	for ( int index = 0; index < controlPoints.len(); index++ )
	{
		bool isEndpoint = index == 0 || index == controlPoints.len() - 1
		entity node = CreateEntity( isEndpoint ? "zipline" : "script_mover_train_node" )
		node.SetOrigin( controlPoints[index] )
		node.SetScriptName( "script_control_omit_zipline" )
		if ( isEndpoint )
		{
			vector direction = index == 0
				? controlPoints[index] - controlPoints[index + 1]
				: controlPoints[index] - controlPoints[index - 1]
			node.SetAngles( VectorToAngles( Normalize( direction ) ) )
			float autoDetachDistance = index == 0
				? startAutoDetachDistance : endAutoDetachDistance
			ReMap_SetZiprailEndpointProperties( node, width, speedScale, autoDetachDistance )
		}
		else
		{
			node.kv.tangent_type = 0
			node.kv.num_smooth_points = -1
			node.kv.perfect_circular_rotation = 0
		}
		nodes.append( node )
	}

	for ( int index = 1; index < nodes.len(); index++ )
		nodes[index].LinkToEnt( nodes[index - 1] )
	foreach ( entity node in nodes )
	{
		DispatchSpawn( node )
		file.entities.append( node )
	}
}

void function ReMap_SetZiprailEndpointProperties( entity endpoint, float width,
	float speedScale, float autoDetachDistance )
{
	endpoint.kv.Material = "cable/zipline.vmt"
	endpoint.kv.DetachEndOnSpawn = 0
	endpoint.kv.DetachEndOnUse = 0
	endpoint.kv.scale = 1
	endpoint.kv.Width = width
	endpoint.kv.ZiplineAutoDetachDistance = autoDetachDistance
	endpoint.kv.ZiplineDropToBottom = 1
	endpoint.kv.ZiplineFadeDistance = -1
	endpoint.kv.ZiplineLengthScale = 1
	endpoint.kv.ZiplinePreserveVelocity = 0
	endpoint.kv.ZiplinePushOffInDirectionX = 0
	endpoint.kv.ZiplineSpeedScale = speedScale
	endpoint.kv.ZiplineVersion = 3
	endpoint.kv.ZiplineVertical = 0
	endpoint.kv.isZiprailStart = 1
	endpoint.kv.ziprailMountReverseDistance = 200
	endpoint.kv.useAutoDetachSpeed = 0
	endpoint.kv.useZiprailAutoDetachSpeed = autoDetachDistance > 0.0 ? 1 : 0
}

void function ReMap_CreateZiprailPointModels( int profile, vector origin,
	vector angles, float supportHeight )
{
	if ( profile == REMAP_ZIPRAIL_POINT_ARM ||
		profile == REMAP_ZIPRAIL_POINT_BUILDING_CLAW_02 ||
		profile == REMAP_ZIPRAIL_POINT_WALL )
	{
		asset armModel = profile == REMAP_ZIPRAIL_POINT_BUILDING_CLAW_02
			? REMAP_ZIPRAIL_MODEL_BUILDING_CLAW_02
			: profile == REMAP_ZIPRAIL_POINT_WALL
				? REMAP_ZIPRAIL_MODEL_WALL
				: REMAP_ZIPRAIL_MODEL_BUILDING_CLAW
		ReMap_CreateZiprailProp( armModel,
			origin + RotateVector( <0, 235, -137>, angles ), angles )
		ReMap_CreateZiprailProp( REMAP_ZIPRAIL_MODEL_CORD_END, origin,
			<angles.x, angles.y + 180.0, angles.z> )
	}
	else if ( profile == REMAP_ZIPRAIL_POINT_SUPPORT )
	{
		supportHeight = clamp( supportHeight, 40.0, 1024.0 )
		ReMap_CreateZiprailProp( REMAP_ZIPRAIL_MODEL_GROUND_BASE,
			origin + RotateVector( <0, 0, -supportHeight>, angles ), angles )
		ReMap_CreateZiprailProp( REMAP_ZIPRAIL_MODEL_GROUND_POST, origin, angles )
		ReMap_CreateZiprailProp( REMAP_ZIPRAIL_MODEL_GROUND_POST_TOP,
			origin + RotateVector( <0, 4, -1>, angles ), angles )
		ReMap_CreateZiprailProp( REMAP_ZIPRAIL_MODEL_GROUND_CLAW,
			origin + RotateVector( <-172, 0, 85>, angles ), angles )
		ReMap_CreateZiprailProp( REMAP_ZIPRAIL_MODEL_CORD_END, origin,
			<angles.x, angles.y + 90.0, angles.z> )
	}
}

entity function ReMap_CreateZiprailProp( asset model, vector origin, vector angles )
{
	entity prop = CreateEntity( "prop_dynamic" )
	prop.SetOrigin( origin )
	prop.SetAngles( angles )
	prop.SetValueForModelKey( model )
	prop.kv.solid = 0
	prop.kv.contents = 0
	DispatchSpawn( prop )
	file.entities.append( prop )
	return prop
}
