// Generated by ReMap for R5Reloaded.
// Source code: https://github.com/ReMap
// Do not edit this file directly; rebuild it from the ReMap sources.

/*
 * ReMap game scripts
 *
 * Source lineage: rewritten from the active R5Reloaded ReMap implementation
 * and the legacy ReMap scripts.
 * Original ReMap: Zee (@AyeZeeBB on X, zee_x64 on Discord)
 * and Julefox (@Julefox_ on X, julefox on Discord).
 * This standalone ReMap rewrite was created and is maintained by Julefox.
 *
 * Made with love for the Apex modding community. <3
 * Built on the Apex modding foundation created by Amos (@AmosModz on X, amosmodz on Discord):
 * https://github.com/Mauler125/r5sdk
 */

global function ReMap_ClearProps
global function ReMap_CreateProp
global function ReMap_CreateDoor
global function ReMap_CreateLootBin
global function ReMap_CreateJumpPad
global function ReMap_CreateSpawnPoint
global function ReMap_CreateTrigger
global function ReMap_CreateJumpTower
global function ReMap_CreateWeaponRack

global const int REMAP_DOOR_SINGLE = 0
global const int REMAP_DOOR_DOUBLE = 1
global const int REMAP_DOOR_VERTICAL = 2
global const int REMAP_DOOR_HORIZONTAL = 3

const asset REMAP_DOOR_MODEL_SINGLE = $"mdl/door/canyonlands_door_single_02.rmdl"
const asset REMAP_DOOR_MODEL_VERTICAL = $"mdl/door/door_canyonlands_large_01_animated.rmdl"
const asset REMAP_DOOR_MODEL_HORIZONTAL = $"mdl/door/door_256x256x8_elevatorstyle02_animated.rmdl"
const asset REMAP_LOOT_BIN_MODEL = $"mdl/props/loot_bin/loot_bin_01_animated.rmdl"
const asset REMAP_JUMP_PAD_MODEL = $"mdl/props/octane_jump_pad/octane_jump_pad.rmdl"
const asset REMAP_JUMP_TOWER_BASE_MODEL = $"mdl/props/zipline_balloon/zipline_balloon_base.rmdl"
const asset REMAP_JUMP_TOWER_BALLOON_MODEL = $"mdl/props/zipline_balloon/zipline_balloon.rmdl"
const asset REMAP_WEAPON_RACK_MODEL = $"mdl/industrial/gun_rack_arm_down.rmdl"
const asset REMAP_WEAPON_RACK_RESPAWN_FX = $"P_impact_shieldbreaker_sparks"
const vector REMAP_WEAPON_RACK_ITEM_OFFSET = < 0, 0, 45 >
const vector REMAP_WEAPON_RACK_ITEM_ANGLES = < -90, 180, 0 >

struct
{
	array< entity > props
} file

void function ReMap_ClearProps()
{
	foreach ( entity prop in file.props )
	{
		if ( IsValid( prop ) )
			prop.Destroy()
	}

	file.props.clear()
}

entity function ReMap_CreateProp( asset model, vector origin, vector angles, bool allowMantle = true, float fadeDistance = 50000.0, int realmId = -1, float scale = 1.0 )
{
	entity prop = CreatePropDynamic( model, origin, angles, SOLID_VPHYSICS, fadeDistance )
	prop.kv.fadedist = fadeDistance
	prop.kv.rendermode = 0
	prop.kv.renderamt = 1
	prop.kv.solid = 6
	prop.kv.CollisionGroup = TRACE_COLLISION_GROUP_PLAYER
	prop.SetScriptName( "remap_prop" )
	prop.SetModelScale( scale )

	if ( allowMantle )
		prop.AllowMantle()

	if ( realmId > -1 )
	{
		prop.RemoveFromAllRealms()
		prop.AddToRealm( realmId )
	}
	prop.e.gameModeId = realmId

	file.props.append( prop )
	return prop
}

void function ReMap_CreateDoor( vector origin, vector angles, int type = REMAP_DOOR_SINGLE, bool gold = false, bool spawnOpen = false )
{
	switch ( type )
	{
		case REMAP_DOOR_SINGLE:
		{
			entity door = ReMap_CreateDoorEntity( "prop_door", REMAP_DOOR_MODEL_SINGLE, "", origin, angles, gold )
			DispatchSpawn( door )
			if ( spawnOpen )
				ReMap_OpenCodeDoorAtSpawn( door )
			file.props.append( door )
			break
		}

		case REMAP_DOOR_DOUBLE:
		{
			entity door = ReMap_CreateDoorEntity( "prop_door", REMAP_DOOR_MODEL_SINGLE, "", origin, angles, gold )
			door.SetOrigin( origin + door.GetRightVector() * 60.0 )
			DispatchSpawn( door )

			entity oppositeDoor = ReMap_CreateDoorEntity( "prop_door", REMAP_DOOR_MODEL_SINGLE, "", origin,
				< -angles.x, angles.y + 180.0, -angles.z >, gold )
			oppositeDoor.SetOrigin( origin + oppositeDoor.GetRightVector() * 60.0 )
			oppositeDoor.LinkToEnt( door )
			DispatchSpawn( oppositeDoor )

			if ( spawnOpen )
				ReMap_OpenCodeDoorAtSpawn( door )
			file.props.append( door )
			file.props.append( oppositeDoor )
			break
		}

		case REMAP_DOOR_VERTICAL:
		{
			entity door = ReMap_CreateDoorEntity( "prop_dynamic", REMAP_DOOR_MODEL_VERTICAL,
				"survival_door_plain", origin, angles, false )
			DispatchSpawn( door )
			if ( spawnOpen )
				ReMap_OpenPlainDoorAtSpawn( door )
			file.props.append( door )
			break
		}

		case REMAP_DOOR_HORIZONTAL:
		{
			entity door = ReMap_CreateDoorEntity( "prop_dynamic", REMAP_DOOR_MODEL_HORIZONTAL,
				"survival_door_plain", origin, angles, false )
			DispatchSpawn( door )
			if ( spawnOpen )
				ReMap_OpenPlainDoorAtSpawn( door )
			file.props.append( door )
			break
		}
	}
}

entity function ReMap_CreateDoorEntity( string entityType, asset model, string scriptName,
	vector origin, vector angles, bool gold )
{
	entity door = CreateEntity( entityType )
	door.SetOrigin( origin )
	door.SetAngles( angles )
	door.SetValueForModelKey( model )

	if ( scriptName != "" )
	{
		door.SetScriptName( scriptName )
		door.kv.solid = 6
	}
	if ( gold )
		door.SetSkin( 1 )

	return door
}

void function ReMap_OpenCodeDoorAtSpawn( entity door )
{
	entity fakeUser = CreateEntity( "prop_dynamic" )
	fakeUser.SetOrigin( door.GetOrigin() - door.GetForwardVector() * 100.0 )
	door.OpenDoor( fakeUser )
	fakeUser.Destroy()
}

void function ReMap_OpenPlainDoorAtSpawn( entity door )
{
	PlayAnimNoWait( door, "open" )
	door.e.isOpen = true
	GradeFlagsSet( door, eGradeFlags.IS_OPEN )
	door.SetUsePrompts( "#SURVIVAL_CLOSE_DOOR", "#SURVIVAL_CLOSE_DOOR" )
}

entity function ReMap_CreateLootBin( vector origin, vector angles, int skin = 0 )
{
	entity lootBin = CreateEntity( "prop_dynamic" )
	lootBin.SetScriptName( LOOT_BIN_SCRIPTNAME )
	lootBin.SetValueForModelKey( REMAP_LOOT_BIN_MODEL )
	lootBin.SetOrigin( origin )
	lootBin.SetAngles( angles )
	lootBin.kv.solid = SOLID_VPHYSICS
	DispatchSpawn( lootBin )
	lootBin.SetSkin( skin )
	file.props.append( lootBin )
	return lootBin
}

entity function ReMap_CreateJumpPad( vector origin, vector angles, bool allowMantle = true,
	float fadeDistance = 50000.0, int realmId = -1, float scale = 1.0,
	float launchVelocity = 1000.0, float forwardScale = 1.7, float radius = 45.0,
	bool doubleJump = true )
{
	entity jumpPad = ReMap_CreateProp( REMAP_JUMP_PAD_MODEL, origin, angles, allowMantle,
		fadeDistance, realmId, scale )
	jumpPad.SetScriptName( "remap_jump_pad" )
	jumpPad.kv.contents = CONTENTS_HITBOX | CONTENTS_BULLETCLIP
	PlayAnimNoWait( jumpPad, "prop_octane_jump_pad_deploy_idle" )

	entity trigger = CreateEntity( "trigger_cylinder_heavy" )
	trigger.SetOwner( jumpPad )
	trigger.SetRadius( radius * scale )
	trigger.SetAboveHeight( 32.0 * scale )
	trigger.SetBelowHeight( 16.0 * scale )
	trigger.SetOrigin( origin )
	trigger.SetAngles( angles )
	trigger.SetTriggerType( TT_JUMP_PAD )
	trigger.SetLaunchScaleValues( launchVelocity, forwardScale )
	trigger.SetViewPunchValues( 15.0, 4.0, 0.0 )
	trigger.UsePointCollision()
	trigger.kv.triggerFilterNonCharacter = "0"
	trigger.s.remapDoubleJump <- doubleJump
	DispatchSpawn( trigger )
	trigger.SetEnterCallback( ReMap_OnJumpPadEnter )
	trigger.SetParent( jumpPad )
	trigger.RemoveFromAllRealms()
	trigger.AddToOtherEntitysRealms( jumpPad )
	file.props.append( trigger )
	return jumpPad
}

void function ReMap_OnJumpPadEnter( entity trigger, entity ent )
{
	if ( !IsValid( ent ) || !ent.IsPlayer() )
		return

	entity jumpPad = trigger.GetOwner()
	if ( IsValid( jumpPad ) )
		PlayAnimNoWait( jumpPad, "prop_octane_jump_pad_deploy_trans" )

	ent.kv.gravity = 0.75
	JumpPadPushEnt( trigger, ent, trigger.GetOrigin(), trigger.GetAngles() )
	thread ReMap_RestoreJumpPadGravity( ent )
	if ( trigger.s.remapDoubleJump )
		thread ReMap_GiveJumpPadDoubleJump( ent )
}

void function ReMap_RestoreJumpPadGravity( entity player )
{
	player.EndSignal( "OnDeath" )
	player.EndSignal( "OnDestroy" )
	OnThreadEnd( function() : ( player )
	{
		if ( IsValid( player ) )
			player.kv.gravity = 1.0
	} )

	WaitFrame()
	while ( IsValid( player ) && !player.IsOnGround() && !player.IsZiplining() )
		WaitFrame()
}

void function ReMap_GiveJumpPadDoubleJump( entity player )
{
	if ( !IsValid( player ) || !player.IsPlayer() )
		return

	player.EndSignal( "OnDeath" )
	player.EndSignal( "OnDestroy" )
	wait 0.1
	if ( !IsValid( player ) || player.IsOnGround() )
		return

	asset storedSettings = player.GetPlayerSettings()
	array< string > storedMods = clone player.GetPlayerSettingsMods()
	array< string > newMods = clone storedMods
	bool alreadyEnabled = false
	foreach ( string mod in newMods )
	{
		if ( mod == "enable_doublejump" )
			alreadyEnabled = true
	}
	if ( !alreadyEnabled )
		newMods.append( "enable_doublejump" )

	int health = player.GetHealth()
	int shields = player.GetShieldHealth()
	player.SetPlayerSettingsWithMods( storedSettings, newMods )
	player.SetHealth( health )
	player.SetShieldHealth( shields )
	AddButtonPressedPlayerInputCallback( player, IN_JUMP, ReMap_ConsumeJumpPadDoubleJump )

	OnThreadEnd( function() : ( player, storedSettings, storedMods )
	{
		if ( !IsValid( player ) )
			return
		RemoveButtonPressedPlayerInputCallback( player, IN_JUMP, ReMap_ConsumeJumpPadDoubleJump )
		if ( IsAlive( player ) )
		{
			int currentHealth = player.GetHealth()
			int currentShields = player.GetShieldHealth()
			player.SetPlayerSettingsWithMods( storedSettings, storedMods )
			player.SetHealth( currentHealth )
			player.SetShieldHealth( currentShields )
		}
	} )

	while ( IsValid( player ) && !player.IsOnGround() && !player.IsZiplining() )
		WaitFrame()
}

void function ReMap_ConsumeJumpPadDoubleJump( entity player )
{
	if ( !IsValid( player ) || !IsAlive( player ) )
		return
	player.ConsumeDoubleJump()
	RemoveButtonPressedPlayerInputCallback( player, IN_JUMP, ReMap_ConsumeJumpPadDoubleJump )
}

entity function ReMap_CreateSpawnPoint( vector origin, vector angles, int teamNumber = 0 )
{
	entity spawnPoint = CreateEntity( "info_spawnpoint_human" )
	spawnPoint.SetOrigin( origin )
	spawnPoint.SetAngles( angles )
	spawnPoint.SetValueForModelKey( $"mdl/dev/mp_spawn.rmdl" )
	spawnPoint.kv.teamnumber = teamNumber
	spawnPoint.kv.control_teamnumber = -1
	spawnPoint.kv.phase_1 = 0
	spawnPoint.kv.phase_2 = 0
	spawnPoint.kv.phase_3 = 0
	spawnPoint.kv.phase_4 = 0
	spawnPoint.kv.phase_5 = 0
	spawnPoint.kv.phase_6 = 0
	spawnPoint.kv.phase_7 = 0
	spawnPoint.kv.phase_8 = 0
	spawnPoint.kv.phase_9 = 0
	spawnPoint.kv.gamemode_tdm = 1
	spawnPoint.kv.gamemode_ffa = 1
	spawnPoint.kv.gamemode_fd = 1
	spawnPoint.kv.gamemode_ctf = 1
	spawnPoint.kv.gamemode_cp = 1
	spawnPoint.kv.gamemode_at = 1
	spawnPoint.kv.gamemode_fw = 0
	spawnPoint.kv.gamemode_freelance = 0
	DispatchSpawn( spawnPoint )
	file.props.append( spawnPoint )
	return spawnPoint
}

entity function ReMap_CreateTrigger( vector origin, vector angles, float radius,
	float halfHeight, bool debugDraw = false, int realmId = -1 )
{
	entity trigger = CreateEntity( "trigger_cylinder" )
	trigger.SetRadius( radius )
	trigger.SetAboveHeight( halfHeight )
	trigger.SetBelowHeight( halfHeight )
	trigger.SetOrigin( origin )
	trigger.SetAngles( angles )
	if ( realmId > -1 )
	{
		trigger.RemoveFromAllRealms()
		trigger.AddToRealm( realmId )
	}
	if ( debugDraw )
	{
		DebugDrawCylinder( origin, < -90, 0, 0 >, radius, halfHeight,
			0, 165, 255, true, 9999.9 )
		DebugDrawCylinder( origin, < -90, 0, 0 >, radius, -halfHeight,
			255, 90, 0, true, 9999.9 )
	}
	file.props.append( trigger )
	return trigger
}

void function ReMap_CreateJumpTower( vector origin, vector angles, float height = 2000.0 )
{
	vector towerAngles = < 0, angles.y, 0 >
	entity towerBase = CreateEntity( "prop_dynamic" )
	towerBase.SetOrigin( origin )
	towerBase.SetAngles( towerAngles )
	towerBase.SetValueForModelKey( REMAP_JUMP_TOWER_BASE_MODEL )
	towerBase.kv.solid = 6
	towerBase.AllowMantle()

	entity balloon = CreateEntity( "prop_dynamic" )
	balloon.SetOrigin( origin + < 0, 0, height > )
	balloon.SetAngles( towerAngles )
	balloon.SetValueForModelKey( REMAP_JUMP_TOWER_BALLOON_MODEL )
	balloon.kv.solid = 3

	foreach ( entity part in [ towerBase, balloon ] )
	{
		part.kv.fadedist = -1
		part.kv.renderamt = 255
		part.kv.rendercolor = "255 255 255"
		part.kv.CollisionGroup = TRACE_COLLISION_GROUP_PLAYER
		part.SetScriptName( "jump_tower" )
		DispatchSpawn( part )
		file.props.append( part )
	}

	vector topCable = PositionOffsetFromEnt( balloon, -1.75, -2.75, 0 )
	vector bottomCable = PositionOffsetFromEnt( towerBase, -1.75, -2.75, 64 )
	ReMap_CreateZipline( topCable, towerAngles, bottomCable, towerAngles,
		REMAP_ZIPLINE_END_NONE, REMAP_ZIPLINE_END_NONE, true, 2.0, 1.0,
		180.0, 180.0, true, 1.0, angles.y, -1.0, 1.0,
		false, true, 200.0, 200.0, false, false, false )

	entity skydiveTrigger = ReMap_CreateTrigger( origin + < 0, 0, height - 20.0 >,
		towerAngles, 200.0, 200.0, false, -1 )
	skydiveTrigger.SetEnterCallback( ForcedSkydiveTriggerThink_EnterCallback )
	DispatchSpawn( skydiveTrigger )
}

entity function ReMap_CreateWeaponRack( vector origin, vector angles, string weaponName,
	float respawnTime = 0.5 )
{
	entity rack = CreateEntity( "prop_dynamic" )
	rack.SetScriptName( "weaponrack_spawned" )
	rack.SetValueForModelKey( REMAP_WEAPON_RACK_MODEL )
	rack.SetOrigin( origin )
	rack.SetAngles( angles )
	rack.kv.solid = SOLID_VPHYSICS
	rack.AllowMantle()
	DispatchSpawn( rack )
	file.props.append( rack )

	entity weapon = ReMap_SpawnWeaponRackItem( rack, weaponName )
	if ( IsValid( weapon ) )
		thread ReMap_WeaponRackRespawnThread( rack, weapon, weaponName, respawnTime )
	return rack
}

entity function ReMap_SpawnWeaponRackItem( entity rack, string weaponName )
{
	if ( !IsValid( rack ) || weaponName.len() == 0 )
		return null

	entity weapon = SpawnGenericLoot( weaponName,
		rack.GetOrigin() + REMAP_WEAPON_RACK_ITEM_OFFSET,
		rack.GetAngles() + REMAP_WEAPON_RACK_ITEM_ANGLES,
		1, TRACE_COLLISION_GROUP_NONE, false, 0, true )
	if ( !IsValid( weapon ) )
		return null
	weapon.SetParent( rack )
	return weapon
}

void function ReMap_WeaponRackRespawnThread( entity rack, entity weapon, string weaponName,
	float respawnTime )
{
	rack.EndSignal( "OnDestroy" )
	weapon.WaitSignal( "OnItemPickup" )
	wait respawnTime

	if ( !IsValid( rack ) )
		return
	entity replacement = ReMap_SpawnWeaponRackItem( rack, weaponName )
	if ( !IsValid( replacement ) )
		return
	StartParticleEffectInWorld( GetParticleSystemIndex( REMAP_WEAPON_RACK_RESPAWN_FX ),
		replacement.GetOrigin(), replacement.GetAngles() )
	thread ReMap_WeaponRackRespawnThread( rack, replacement, weaponName, respawnTime )
}
