param(
    [string]$OutputRoot = (Join-Path (Split-Path -Parent $PSScriptRoot) 'scripts/vscripts'),
    [string]$SourceRepositoryUrl = 'https://github.com/R5Reloaded-ReMap/ReMap',
    [switch]$Check
)

$ErrorActionPreference = 'Stop'
$projectRoot = Split-Path -Parent $PSScriptRoot
$sourceRoot = Join-Path $projectRoot 'scripts/vscripts/source'
$utf8 = [Text.UTF8Encoding]::new($false)
$sourceNamePattern = '^((?:sv_|cl_|sh_|ui_|_)[a-z0-9_]+)\.source\.(nut|gnut)$'
$templateNamePattern = '^((?:sv_|cl_|sh_|ui_|_)[a-z0-9_]+)\.(nut|gnut)$'

function Get-ReMapSources {
    if (!(Test-Path -LiteralPath $sourceRoot -PathType Container)) {
        throw "Missing game-script source directory: $sourceRoot"
    }

    $sources = [Collections.Generic.List[object]]::new()
    foreach ($file in @(Get-ChildItem -LiteralPath $sourceRoot -File | Sort-Object Name)) {
        $rawTemplate = $false
        if ($file.Name -match $sourceNamePattern) { }
        elseif ($file.Name -match $templateNamePattern) { $rawTemplate = $true }
        else { continue }
        [void]$sources.Add([pscustomobject]@{
            Path = $file.FullName
            BaseName = $Matches[1]
            Extension = '.' + $Matches[2]
            RawTemplate = $rawTemplate
        })
    }

    if ($sources.Count -eq 0) { throw "No game-script sources found in $sourceRoot." }
    return $sources
}

function Expand-ReMapSource([string]$path, [string]$symbol, [bool]$rawTemplate) {
    if ($rawTemplate) { return ([IO.File]::ReadAllText($path) -replace "`r`n", "`n").TrimEnd() }
    $lines = ([IO.File]::ReadAllText($path) -replace "`r`n", "`n") -split "`n"
    $stack = [Collections.Generic.List[object]]::new()
    $active = $true
    $output = [Text.StringBuilder]::new()

    foreach ($line in $lines) {
        if ($line -match '^\s*#if\s+(R5F|R5R)\s*$') {
            $frame = [pscustomobject]@{
                Kind = 'Target'
                ParentActive = $active
                Condition = ($Matches[1] -eq $symbol)
                ElseSeen = $false
            }
            [void]$stack.Add($frame)
            $active = $frame.ParentActive -and $frame.Condition
            continue
        }
        if ($line -match '^\s*#if\s+.+$') {
            $frame = [pscustomobject]@{ Kind = 'Runtime'; ParentActive = $active; Condition = $true; ElseSeen = $false }
            [void]$stack.Add($frame)
            if ($active) { [void]$output.AppendLine($line) }
            continue
        }
        if ($line -match '^\s*#elseif\s+.+$') {
            if ($stack.Count -eq 0 -or $stack[$stack.Count - 1].Kind -ne 'Runtime') { throw "#elseif without runtime #if in $path." }
            if ($stack[$stack.Count - 1].ParentActive) { [void]$output.AppendLine($line) }
            continue
        }
        if ($line -match '^\s*#else\s*$') {
            if ($stack.Count -eq 0) { throw "#else without #if in $path." }
            $frame = $stack[$stack.Count - 1]
            if ($frame.ElseSeen) { throw "Duplicate #else in $path." }
            $frame.ElseSeen = $true
            if ($frame.Kind -eq 'Target') { $active = $frame.ParentActive -and !$frame.Condition }
            elseif ($frame.ParentActive) { [void]$output.AppendLine($line) }
            continue
        }
        if ($line -match '^\s*#endif(?:\s*//.*)?\s*$') {
            if ($stack.Count -eq 0) { throw "#endif without #if in $path." }
            $frame = $stack[$stack.Count - 1]
            $stack.RemoveAt($stack.Count - 1)
            if ($frame.Kind -eq 'Runtime' -and $frame.ParentActive) { [void]$output.AppendLine($line) }
            $active = $frame.ParentActive
            continue
        }
        if ($line -match '^\s*#(?:file|endfile)\b') {
            throw "Legacy #file directives are not allowed in $path. Use one .source file per output file."
        }
        if ($line -match '^\s*#') { throw "Unknown game-script directive in $path`: $line" }
        if ($active) { [void]$output.AppendLine($line) }
    }

    if ($stack.Count -ne 0) { throw "Missing #endif in $path." }
    return $output.ToString().TrimEnd()
}

function Build-ReMapVariant([string]$target, [string]$symbol, [string]$folderName, [object[]]$sources) {
    $targetRoot = Join-Path $OutputRoot $folderName
    $expected = [Collections.Generic.HashSet[string]]::new([StringComparer]::OrdinalIgnoreCase)
    $outputs = [Collections.Generic.List[string]]::new()

    foreach ($source in $sources) {
        $header = "// Generated by ReMap for $target.`n// Source code: $SourceRepositoryUrl`n// Do not edit this file directly; rebuild it from the ReMap sources.`n`n"
        $content = ($header + (Expand-ReMapSource $source.Path $symbol $source.RawTemplate) + "`n") -replace "`r`n", "`n"
        $fileName = $source.BaseName + $source.Extension
        $outputPath = Join-Path $targetRoot $fileName
        [void]$expected.Add($fileName)

        if ($Check) {
            if (!(Test-Path -LiteralPath $outputPath -PathType Leaf)) { throw "Missing generated game script: $outputPath" }
            $actual = [IO.File]::ReadAllText($outputPath) -replace "`r`n", "`n"
            if ($actual -cne $content) { throw "Generated game script is stale: $outputPath" }
        }
        else {
            [IO.Directory]::CreateDirectory($targetRoot) | Out-Null
            [IO.File]::WriteAllText($outputPath, $content, $utf8)
        }
        [void]$outputs.Add($outputPath)
    }

    if (Test-Path -LiteralPath $targetRoot -PathType Container) {
        $unexpected = @(Get-ChildItem -LiteralPath $targetRoot -File | Where-Object {
            ($_.Extension -eq '.nut' -or $_.Extension -eq '.gnut') -and !$expected.Contains($_.Name)
        })
        if ($unexpected.Count -gt 0) {
            if ($Check) { throw "Unexpected generated game scripts in $targetRoot`: $($unexpected.Name -join ', ')" }
            foreach ($file in $unexpected) {
                $content = [IO.File]::ReadAllText($file.FullName)
                if (!$content.StartsWith('// Generated by ReMap for ')) {
                    throw "Refusing to remove non-generated script: $($file.FullName)"
                }
                Remove-Item -LiteralPath $file.FullName
            }
        }
    }

    return $outputs
}

$sources = @(Get-ReMapSources)
$r5reloaded = @(Build-ReMapVariant 'R5Reloaded' 'R5R' 'remap_r5r' $sources)
$flowstate = @(Build-ReMapVariant 'R5Flowstate' 'R5F' 'remap_r5f' $sources)
Write-Output ($r5reloaded | ForEach-Object { "R5Reloaded: $_" })
Write-Output ($flowstate | ForEach-Object { "R5Flowstate: $_" })
